jobs:
  - deployment: WaitForApproval
    displayName: "🛡️ waiting approval"
    ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      environment: "Deploy develop"
    ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      environment: "Deploy staging"
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      environment: "Deploy master"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "✅ Aprobación recibida. Iniciando el despliegue..."
              displayName: "🔓 Awaiting Approval"

  #####################################################################

  - ${{ if eq(parameters.release, 'ecs-transactions---') }}:
      - template: ./deploy/deploy-transactions.yml
        parameters:
          red: ${{ parameters.red }}
          apps: ${{ parameters.apps }}
