jobs:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - deployment: WaitForApproval
        displayName: "🛡️ waiting approval"
        ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
          environment: "Deploy develop"
        ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
          environment: "Deploy staging"
        ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
          environment: "Deploy master"
        pool:
          name: "Azure Pipelines"
          VmImage: ubuntu-22.04
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "✅ Aprobación recibida. Iniciando el despliegue..."
                  displayName: "🔓 Awaiting Approval"

  #####################################################################

  - ${{ if eq(parameters.release, 'aws-s3') }}:
      - template: ./deploy/deploy-frontend.yml
        parameters:
          apps: ${{ parameters.apps }}
          region: ${{ parameters.region }}
          environments: ${{ parameters.environments }}

      - ${{ if eq(parameters.region, 'antioquia') }}:
          - template: ./commit/commit-version-frontend.yml
            parameters:
              apps: ${{ parameters.apps }}

  #####################################################################

  - ${{ if eq(parameters.release, 'aws-ecs') }}:
      - template: ./deploy/deploy-backend.yml
        parameters:
          region: ${{ parameters.region }}
          environments: ${{ parameters.environments }}

      - ${{ if eq(parameters.region, 'antioquia') }}:
          - template: ./commit/commit-version-backend.yml

  #####################################################################

  - ${{ if eq(parameters.release, 'apk') }}:
      - template: ./deploy/deploy-flutter.yml
        parameters:
          region: ${{ parameters.region }}
          environments: ${{ parameters.environments }}

      - ${{ if eq(parameters.region, 'antioquia') }}:
          - template: ./commit/commit-version-flutter.yml

  #####################################################################

  - ${{ if eq(parameters.release, 'app') }}:
      - template: ./deploy/deploy-electron.yml
        parameters:
          region: ${{ parameters.region }}
          environments: ${{ parameters.environments }}

      - ${{ if eq(parameters.region, 'antioquia') }}:
          - template: ./commit/commit-version-electron.yml

  #####################################################################

  - ${{ if eq(parameters.release, 'rpc') }}:
      - template: ./deploy/deploy-repository-configuration.yml
        parameters:
          region: ${{ parameters.region }}
          environments: ${{ parameters.environments }}
