jobs:
- job: 'change_file'
  displayName: 'Change File'
  pool:
    name: 'Azure Pipelines'
    VmImage: ubuntu-22.04
  steps:
    - checkout: self
      fetchDepth: 0
  
    - script: |
        cd $(Build.SourcesDirectory)/apps
        apps=$(git diff --name-only HEAD~1 HEAD | grep "^apps/" | cut -d '/' -f2 | sort -u)
        echo $apps

        cd $(Build.SourcesDirectory)/pipeline

        apps_yaml="    apps:\n"
        for app in $apps; do
          apps_yaml+="      - $app\n"
        done

        # Reemplazar el bloque `apps:` en main-pipeline.yml
        awk -v newapps="$apps_yaml" '
          BEGIN {inside=0}
          /^    apps:/ {inside=1; print newapps; next}
          inside && /^[^ ]/ {inside=0}
          !inside
        ' main-pipeline.yml > main-pipeline-updated.yml

        mv main-pipeline-updated.yml main-pipeline.yml

        cat main-pipeline.yml

      name: DetectChangedMS
    
    - script: az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
      displayName: 'Set default Azure DevOps organization and project'

    - script: |
          echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
          az pipelines run --name "Pruebas-consumir-template" \
          --branch "$(Build.SourceBranchName)" \
          --project "$(System.TeamProject)" \
          --org "https://dev.azure.com/ux-technology"
      env:
        AZURE_DEVOPS_CLI_PAT: $(PAT-AZ)
      displayName: 'Trigger pipeline'

    # - script: |
    #     echo $(DetectChangedMS.changedMs)
    #     CHANGED_MS_LIST=$(echo "$(DetectChangedMS.changedMs)" | xargs -n1 | jq -R . | jq -s .)
    #     echo $CHANGED_MS_LIST
    #     for ms in $(echo "$CHANGED_MS_LIST" | jq -r '.[]'); do
    #       echo "Procesando microservicio: $ms"
    #       VERSION=$(jq -r '.version' "$(Build.SourcesDirectory)/apps/$ms/package.json")
    #       echo "Versión de $ms: $VERSION"
    #       echo "##vso[task.setvariable variable=${ms}_version]$VERSION"
    #     done
    #   displayName: "Obtener versiones de los MS cambiados"