parameters:
  - name: red
    type: object
    default:
      - antioquia
      - cap
      # - tolima
      # - huila
      # - cauca
      # - boyaca

  - name: apps
    type: object
    default:
      - "app-administration-vue2"
      # - "app-sellers-vue2"
      # - "awards"
      # - "biometrics"
      # - "commissions"
      # - "conciliation"
      # - "dashboard"
      # - "dynamic-storage"
      # - "external-wager"
      # - "hierarchies"
      # - "invictus"
      # - "login"
      # - "lotteries"
      # - "money-control"
      # - "users"

  - name: release
    type: string

resources:
  repositories:
    - repository: self
      name: $(System.TeamProject)/$(Build.Repository.Name)
      type: git
      ref: $(Build.SourceBranch)

    - repository: electron
      name: Invictus/electron-app-invictus
      type: git
      ref: refs/heads/master

stages:
  #
  # MicroFronted pipeline
  #
  - ${{ if and(eq(parameters.release, 'aws-s3'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/staging'), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))) }}:
      - template: pipelines/pipeline-micro-fronted.yml
        parameters:
          red: ${{ parameters.red }}
          apps: ${{ parameters.apps }}
          release: ${{ parameters.release }}

  #
  # Electron pipeline
  #
  - ${{ if and(eq(parameters.release, 'exe'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/staging'), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))) }}:
      - template: pipeline/pipeline-electron.yml
        parameters:
          red: ${{ parameters.red }}
          release: ${{ parameters.release }}
