parameters:
  - name: release
    type: string
    values:
      - ecs-networks

  - name: red
    type: object
    default:
      # - antioquia
      - cap
      - tolima
      - huila
      - cauca
      - boyaca
      - santander

  - name: apps
    type: object
    default:
      microservice-lotteries-games: "4.14.2"
      microservice-transaction: "4.5.16"
      microservice-transaction-astro: "4.5.16"
      microservice-transaction-lotteries-games: "4.5.16"
      microservice-transaction-recharges: "4.5.16"

resources:
  repositories:
    - repository: self
      name: $(System.TeamProject)/$(Build.Repository.Name)
      type: git
      ref: $(Build.SourceBranch)

stages:
  #
  # DEPLOY REDES MOMENTANEMENTE
  #
  - ${{ if and(eq(parameters.release, 'ecs-networks'), eq(variables['Build.SourceBranchName'], 'master')) }}:
      - template: pipelines/pipeline-ecs-networks.yml
        parameters:
          red: ${{ parameters.red }}
          apps: ${{ parameters.apps }}
          release: ${{ parameters.release }}
