parameters:
  - name: release
    type: string

  - name: environments_new_staging
    type: object
    default:
      - staging_nacional
      # - staging_new

  - name: red
    type: object
    default:
      - antioquia
      - cap
      # - tolima
      - huila
      - cauca
      - boyaca
      - santander
      - putumayo

resources:
  repositories:
    - repository: self
      name: $(System.TeamProject)/$(Build.Repository.Name)
      type: git

stages:
  #
  # Infrastructure pipeline
  #
  - ${{ if and(eq(parameters.release, 'iac'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), in(variables['Build.SourceBranchName'], 'develop', 'staging', 'master'))) }}:
      - template: ./pipelines/pipeline-infrastructure.yml
        parameters:
          red: ${{ parameters.red }}
          release: ${{ parameters.release }}
          environments_new_staging: ${{ parameters.environments_new_staging }}
