stages:
  - stage: "semantic_version_transactions"
    displayName: "🏷️ Semantic Version Transactions"
    jobs:
      - template: ../ci/semantic-version-transactions.yml
        parameters:
          apps: ${{ parameters.apps }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: deploy_transactions_${{ region }}
            displayName: "🚀 Deploy Transactions Antioquia"
            dependsOn: semantic_version_transactions
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  red: ${{ region }}
                  apps: ${{ parameters.apps }}
                  release: ${{ parameters.release }}
