stages:
  - stage: semantic_version_micro_fronted
    displayName: "🏷️ Semantic Version MicroFrontend"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          apps: ${{ parameters.apps }}
          release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: build_micro_frontend_${{ region }}
            displayName: "📦 Build MicroFrontend ${{ region }}"
            dependsOn: semantic_version_micro_fronted
            jobs:
              - template: ../ci/build/build-frontend.yml
                parameters:
                  region: ${{ region }}
                  apps: ${{ parameters.apps }}
                  pr_id: ${{ parameters.pr_id }}

          - stage: deploy_micro_frontend_${{ region }}
            displayName: "🚀 Deploy MicroFrontend ${{ region }}"
            dependsOn: build_micro_frontend_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  apps: ${{ parameters.apps }}
                  release: ${{ parameters.release }}

  # #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - stage: build_micro_frontend
        displayName: "📦 Build MicroFrontend"
        dependsOn: semantic_version_micro_fronted
        jobs:
          - template: ../ci/build/build-frontend.yml
            parameters:
              apps: ${{ parameters.apps }}

      - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
          - stage: check_build_micro_frontend
            displayName: "🛡️ Check Build MicroFrontend"
            dependsOn: build_micro_frontend
            condition: ne('${{ parameters.pr_id }}', '0')
            jobs:
              - template: ../ci/pre-build/check-build-frontend.yml
                parameters:
                  pr_id: ${{ parameters.pr_id }}

      - ${{ if in(variables['Build.SourceBranchName'], 'develop', 'staging') }}:
          - stage: deploy_micro_frontend
            displayName: "🚀 Deploy MicroFrontend"
            dependsOn: build_micro_frontend
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  apps: ${{ parameters.apps }}
                  release: ${{ parameters.release }}
