stages:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: build_repository_configuration_${{ region }}
            displayName: "📦 Repository Configuration ${{ region }}"
            jobs:
              - template: ../ci/build/build-repository-configuration.yml
                parameters:
                  region: ${{ region }}

          - stage: deploy_repository_configuration_${{ region }}
            displayName: "🚀 Deploy Repository Configuration ${{ region }}"
            dependsOn: build_repository_configuration_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: rpc
                  region: ${{ region }}

  #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - stage: build_repository_configuration
        displayName: "📦 Repository Configuration"
        jobs:
          - template: ../ci/build/build-repository-configuration.yml

      - stage: deploy_repository_configuration
        displayName: "🚀 Repository Configuration"
        dependsOn: build_repository_configuration
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: rpc
