stages:
  - stage: semantic_version_repository_configuration
    displayName: "🏷️ Semantic Version Repository Configuration"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: build_repository_configuration_${{ region }}
            displayName: "📦 Repository Configuration ${{ region }}"
            dependsOn: semantic_version_repository_configuration
            jobs:
              - template: ../ci/build/build-repository-configuration.yml
                parameters:
                  region: ${{ region }}

          - stage: deploy_repository_configuration_${{ region }}
            displayName: "🚀 Deploy Repository Configuration ${{ region }}"
            dependsOn: build_repository_configuration_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}

  #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - stage: build_repository_configuration
        displayName: "📦 Repository Configuration"
        dependsOn: semantic_version_repository_configuration
        jobs:
          - template: ../ci/build/build-repository-configuration.yml

      - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
          - stage: deploy_repository_configuration_develop
            displayName: "🚀 Deploy Repository Configuration develop"
            dependsOn: build_repository_configuration
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: ${{ parameters.release }}

      - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
          - ${{ each environment_staging in parameters.environments_staging }}:
              - stage: deploy_repository_configuration_${{ environment_staging }}
                displayName: "🚀 Deploy Repository Configuration ${{ environment_staging }}"
                dependsOn: build_repository_configuration
                jobs:
                  - template: ../cd/deployment.yml
                    parameters:
                      release: ${{ parameters.release }}
                      environment_staging: ${{ environment_staging }}
