stages:
  - stage: semantic_version_micro_services
    displayName: "🏷️ Semantic Version Microservice"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')) }}:
      - stage: sonar_micro_services
        displayName: "🛡️ Sonarqube Microservice"
        dependsOn: semantic_version_micro_services
        jobs:
          - template: ../ci/sonar/sonar-backend.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:

      - stage: build_micro_services_master
        displayName: "📦 Build Microservice Master"
        dependsOn: semantic_version_micro_services
        jobs:
          - template: ../ci/build/build-backend.yml

      - ${{ each region in parameters.red }}:
          - stage: deploy_micro_services_${{ region }}
            displayName: "🚀 Deploy Microservice ${{ region }}"
            dependsOn: build_micro_services_master
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - stage: build_micro_services
        displayName: "📦 Build Microservice"
        dependsOn: test_micro_services
        jobs:
          - template: ../ci/build/build-backend.yml

  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      - stage: build_micro_services
        displayName: "📦 Build Microservice"
        dependsOn: semantic_version_micro_services
        jobs:
          - template: ../ci/build/build-backend.yml

  - ${{ if in(variables['Build.SourceBranchName'], 'develop', 'staging') }}:
      - stage: deploy_micro_services
        displayName: "🚀 Deploy Microservice"
        dependsOn: build_micro_services
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: ${{ parameters.release }}
