stages:
  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - stage: "semantic_version_microservices"
        displayName: "🏷️ Semantic Version Microservices"
        jobs:
          - template: ../ci/semantic-version-update.yml

      - stage: deploy_microservices
        displayName: "🚀 Deploy Microservices"
        dependsOn: semantic_version_microservices
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      - ${{ each environment_staging in parameters.environments_staging }}:
          - stage: "semantic_version_microservices_${{ environment_staging }}"
            displayName: "🏷️ Semantic Version Microservices"
            jobs:
              - template: ../ci/semantic-version-update.yml
                parameters:
                  environment_staging: ${{ environment_staging }}

          - stage: deploy_microservices_${{ environment_staging }}
            displayName: "🚀 Deploy Microservices ${{ environment_staging }}"
            dependsOn: semantic_version_microservices_${{ environment_staging }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: ${{ parameters.release }}
                  environment_staging: ${{ environment_staging }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: "semantic_version_microservices_${{ region }}"
            displayName: "🏷️ Semantic Version Microservices"
            jobs:
              - template: ../ci/semantic-version-update.yml
                parameters:
                  region: ${{ region }}

          - stage: deploy_microservices_${{ region }}
            displayName: "🚀 Deploy Microservices ${{ region }}"
            dependsOn: semantic_version_microservices_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}
