stages:
  - stage: semantic_version_artifact
    displayName: "🏷️ Semantic Version Artifact"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), eq(variables['Build.SourceBranchName'], 'develop')) }}:
    - stage: build_artifact
      displayName: "📦 Build Artifact"
      dependsOn: semantic_version_artifact
      jobs:
        - template: ../ci/build/build-artifact.yml

  - ${{ if in(variables['Build.SourceBranchName'], 'develop', 'staging', 'master') }}:
    - stage: deploy_artifact
      displayName: "📦 Deploy Artifact"
      
      ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
        dependsOn: build_artifact
      ${{ if in(variables['Build.SourceBranchName'], 'staging', 'master') }}:
      dependsOn: semantic_version_artifact

      jobs:
        - template: ../cd/deployment.yml
          parameters:
            release: ${{ parameters.release }}