stages:
  - stage: pre_build_microfrontend
    displayName: "🔎 Pre Build MicroFrontend"
    jobs:
      - template: ../ci/pre-build/changes-files-frontend.yml
        parameters:
          release: ${{ parameters.release }}
