stages:
  - stage: semantic_version_flutter
    displayName: "🏷️ Semantic Version Flutter"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  #####################################################################

  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - stage: build_flutter
        displayName: "📦 Build Flutter"
        dependsOn: semantic_version_flutter
        jobs:
          - template: ../ci/build/build-flutter.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - stage: build_flutter_develop
        displayName: "📦 Build Flutter develop"
        dependsOn: semantic_version_flutter
        jobs:
          - template: ../ci/build/build-flutter.yml
            parameters:
              environments: develop

      - stage: deploy_flutter_develop
        displayName: "🚀 Deploy Flutter develop"
        dependsOn: build_flutter_develop
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: ${{ parameters.release }}
              environments: develop

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      - ${{ each environment_staging in parameters.environments_staging }}:
          - stage: build_flutter_${{ environment_staging }}
            displayName: "📦 Build Flutter ${{ environment_staging }}"
            dependsOn: semantic_version_flutter
            jobs:
              - template: ../ci/build/build-flutter.yml
                parameters:
                  environment_staging: ${{ environment_staging }}

          - stage: deploy_flutter_${{ environment_staging }}
            displayName: "🚀 Deploy Flutter ${{ environment_staging }}"
            dependsOn: build_flutter_${{ environment_staging }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: ${{ parameters.release }}
                  environment_staging: ${{ environment_staging }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: build_flutter_${{ region }}
            displayName: "📦 Build Flutter ${{ region }}"
            dependsOn: semantic_version_flutter
            jobs:
              - template: ../ci/build/build-flutter.yml
                parameters:
                  region: ${{ region }}

          - stage: deploy_flutter_${{ region }}
            displayName: "🚀 Deploy Flutter ${{ region }}"
            dependsOn: build_flutter_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}
