stages:
  - stage: semantic_version_flutter
    displayName: "🏷️ Semantic Version Flutter"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
      - stage: build_flutter
        displayName: "📦 Build Flutter"
        dependsOn: semantic_version_flutter
        jobs:
          - template: ../ci/build/build-flutter.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
        # - ${{ if ne(region, 'antioquia_new') }}:
          - stage: build_flutter_${{ region }}
            displayName: "📦 Build Flutter ${{ region }}"
            dependsOn: semantic_version_flutter
            jobs:
              - template: ../ci/build/build-flutter.yml
                parameters:
                  region: ${{ region }}

          - stage: deploy_flutter_${{ region }}
            displayName: "🚀 Deploy Flutter ${{ region }}"
            dependsOn: build_flutter_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}

  #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
          - ${{ each environments in parameters.environments_new_develop }}:
              - stage: build_flutter_${{ environments }}
                displayName: "📦 Build Flutter ${{ environments }}"
                dependsOn: semantic_version_flutter
                jobs:
                  - template: ../ci/build/build-flutter.yml
                    parameters:
                      environments: ${{ environments }}

              - stage: deploy_flutter_${{ environments }}
                displayName: "🚀 Deploy Flutter ${{ environments }}"
                dependsOn: build_flutter_${{ environments }}
                jobs:
                  - template: ../cd/deployment.yml
                    parameters:
                      release: ${{ parameters.release }}
                      environments: ${{ environments }}

      - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
          - ${{ each environments in parameters.environments_new_staging }}:
              - stage: build_flutter_${{ environments }}
                displayName: "📦 Build Flutter ${{ environments }}"
                dependsOn: semantic_version_flutter
                jobs:
                  - template: ../ci/build/build-flutter.yml
                    parameters:
                      environments: ${{ environments }}

              - stage: deploy_flutter_${{ environments }}
                displayName: "🚀 Deploy Flutter ${{ environments }}"
                dependsOn: build_flutter_${{ environments }}
                jobs:
                  - template: ../cd/deployment.yml
                    parameters:
                      release: ${{ parameters.release }}
                      environments: ${{ environments }}
