stages:
  - stage: scan_infrastructure
    displayName: "🛡️ Scan Infrastructure"
    jobs:
      - template: ../ci/scan/sonar-infrastructure.yml
      # - template: ../ci/scan/checkov-infrastructure.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: plan_infrastructure_${{ region }}
            displayName: "🧩 Plan Infrastructure ${{ region }}"
            dependsOn: scan_infrastructure
            jobs:
              - template: ../ci/build/plan-infrastructure.yml
                parameters:
                  region: ${{ region }}

          - stage: apply_infrastructure_${{ region }}
            displayName: "🚀 Apply Infrastructure ${{ region }}"
            dependsOn: plan_infrastructure_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    - stage: plan_infrastructure
      displayName: "🧩 Plan Infrastructure"
      dependsOn: scan_infrastructure
      jobs:
        - template: ../ci/build/plan-infrastructure.yml

    - stage: apply_infrastructure
      displayName: "🚀 Apply Infrastructure"
      dependsOn: plan_infrastructure
      jobs:
        - template: ../cd/deployment.yml
          parameters:
            release: ${{ parameters.release }}
  
  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
    - ${{ each environments in parameters.environments_new_staging }}:
      - stage: plan_infrastructure_${{ environments }}
        displayName: "🧩 Plan Infrastructure ${{ environments }}"
        dependsOn: scan_infrastructure
        jobs:
          - template: ../ci/build/plan-infrastructure.yml
            parameters:
              environments: ${{ environments }}

      - stage: apply_infrastructure_${{ environments }}
        displayName: "🚀 Apply Infrastructure ${{ environments }}"
        dependsOn: plan_infrastructure_${{ environments }}
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: ${{ parameters.release }}
              environments: ${{ environments }}

