stages:
  - stage: semantic_version_micro_service
    displayName: "🏷️ Semantic Version MicroService"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - stage: scan_micro_service
        displayName: "🛡️ Scan MicroService"
        dependsOn: semantic_version_micro_service
        jobs:
          - template: ../ci/tests/sonarqube-microservices.yml
          - template: ../ci/tests/gitleaks.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - stage: build_micro_service
        displayName: "📦 Build MicroService"
        dependsOn: semantic_version_micro_service
        jobs:
          - template: ../ci/build/build-backend.yml

      - ${{ each region in parameters.red }}:
          - stage: deploy_micro_service_${{ region }}
            displayName: "🚀 Deploy MicroService ${{ region }}"
            dependsOn: build_micro_service
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - stage: build_micro_service
        displayName: "📦 Build MicroService"
        dependsOn: scan_micro_service
        jobs:
          - template: ../ci/build/build-backend.yml

      - stage: deploy_micro_service_develop
        displayName: "🚀 Deploy MicroService develop"
        dependsOn: build_micro_service
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: ${{ parameters.release }}

  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      - stage: build_micro_service
        displayName: "📦 Build MicroService"
        dependsOn: semantic_version_micro_service
        jobs:
          - template: ../ci/build/build-backend.yml

      - ${{ each environments in parameters.environments_new_staging }}:
          - stage: deploy_micro_service_${{ environments }}
            displayName: "🚀 Deploy MicroService ${{ environments }}"
            dependsOn: build_micro_service
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  environments: ${{ environments }}
                  release: ${{ parameters.release }}
