stages:
  - stage: semantic_version_electron
    displayName: "🏷️ Semantic Version Electron"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - stage: build_electron
        displayName: "📦 Build Electron"
        dependsOn: semantic_version_electron
        jobs:
          - template: ../ci/build/build-electron.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - ${{ if ne(region, 'antioquia_new') }}:
              - stage: build_electron_${{ region }}
                displayName: "📦 Build Electron ${{ region }}"
                dependsOn: semantic_version_electron
                jobs:
                  - template: ../ci/build/build-electron.yml
                    parameters:
                      region: ${{ region }}

              - stage: deploy_electron_${{ region }}
                displayName: "🚀 Deploy Electron ${{ region }}"
                dependsOn: build_electron_${{ region }}
                jobs:
                  - template: ../cd/deployment.yml
                    parameters:
                      region: ${{ region }}
                      release: ${{ parameters.release }}

  #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
          - stage: build_electron_develop
            displayName: "📦 Build Electron develop"
            dependsOn: semantic_version_electron
            jobs:
              - template: ../ci/build/build-electron.yml

          - stage: deploy_electron_develop
            displayName: "🚀 Deploy Electron develop"
            dependsOn: build_electron_develop
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: ${{ parameters.release }}

      - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
          - ${{ each environment_staging in parameters.environments_staging }}:
              - stage: build_electron_${{ environment_staging }}
                displayName: "📦 Build Electron ${{ environment_staging }}"
                dependsOn: semantic_version_electron
                jobs:
                  - template: ../ci/build/build-electron.yml
                    parameters:
                      environment_staging: ${{ environment_staging }}

              - stage: deploy_electron_${{ environment_staging }}
                displayName: "🚀 Deploy Electron ${{ environment_staging }}"
                dependsOn: build_electron_${{ environment_staging }}
                jobs:
                  - template: ../cd/deployment.yml
                    parameters:
                      release: ${{ parameters.release }}
                      environment_staging: ${{ environment_staging }}
