stages:
  - stage: "semantic_version_microservices"
    displayName: "🏷️ Semantic Version Microservices"
    jobs:
      - template: ../ci/semantic-version-reload.yml
        parameters:
          release: ${{ parameters.release }}
          services: ${{ parameters.services }}

  #####################################################################

  - stage: deploy_microservices
    displayName: "🚀 Reload Microservices"
    dependsOn: semantic_version_microservices
    jobs:
      - template: ../cd/deployment-reload.yml
        parameters:
          release: ${{ parameters.release }}
          services: ${{ parameters.services }}
