stages:
  - stage: semantic_version_electron
    displayName: "🏷️ Semantic Version Electron"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: build_electron_${{ region }}
            displayName: "📦 Build Electron ${{ region }}"
            dependsOn: semantic_version_electron
            jobs:
              - template: ../ci/build/build-electron.yml
                parameters:
                  region: ${{ region }}

          - stage: deploy_electron_${{ region }}
            displayName: "🚀 Deploy Electron ${{ region }}"
            dependsOn: build_electron_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}

  #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:

      - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}: 
        - ${{ each environments in parameters.environments_new_develop }}:
          - stage: build_electron_${{ environments }}
            displayName: "📦 Build Electron ${{ environments }}"
            dependsOn: semantic_version_electron
            jobs:
              - template: ../ci/build/build-electron.yml
                parameters:
                  environments: ${{ environments }}

          - stage: deploy_electron_${{ environments }}
            displayName: "🚀 Deploy Electron ${{ environments }}"
            dependsOn: build_electron_${{ environments }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: ${{ parameters.release }}
                  environments: ${{ environments }}

      - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
        - ${{ each environments in parameters.environments_new_staging }}:
          - stage: build_electron_${{ environments }}
            displayName: "📦 Build Electron ${{ environments }}"
            dependsOn: semantic_version_electron
            jobs:
              - template: ../ci/build/build-electron.yml
                parameters:
                  environments: ${{ environments }}

          - stage: deploy_electron_${{ environments }}
            displayName: "🚀 Deploy Electron ${{ environments }}"
            dependsOn: build_electron_${{ environments }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: ${{ parameters.release }}
                  environments: ${{ environments }}

