stages:
  - stage: "semantic_version_microservices"
    displayName: "🏷️ Semantic Version Microservices"
    jobs:
      - template: ../ci/semantic-version-update.yml
        parameters:
          release: ${{ parameters.release }}

  #####################################################################

  - stage: deploy_microservices
    displayName: "🚀 Deploy Microservices"
    dependsOn: semantic_version_microservices
    jobs:
      - template: ../cd/deployment-update.yml
        parameters:
          release: ${{ parameters.release }}
