stages:
  - stage: "semantic_version_microservices"
    displayName: "🏷️ Semantic Version Microservices"
    jobs:
      - template: ../ci/semantic-version-reload.yml
        parameters:
          services: ${{ parameters.services }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - stage: deploy_microservices
        displayName: "🚀 Reload Microservices"
        dependsOn: semantic_version_microservices
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: ${{ parameters.release }}
              services: ${{ parameters.services }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      - ${{ each environment_staging in parameters.environments_staging }}:
          - stage: deploy_microservices_${{ environment_staging }}
            displayName: "🚀 Reload Microservices ${{ environment_staging }}"
            dependsOn: semantic_version_microservices
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  environment_staging: ${{ environment_staging }}
                  release: ${{ parameters.release }}
                  services: ${{ parameters.services }}
