stages:
  - stage: pre_build_micro_fronted
    displayName: "🏷️ Pre Build MicroFrontend"
    jobs:
      - template: ../ci/pre-build/changes-file-frontend.yml
        parameters:
          release: ${{ parameters.release }}
