stages:
  - stage: semantic_version_integration
    displayName: "🏷️ Semantic Version MicroFrontend"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          apps: ${{ parameters.apps }}
          release: ${{ parameters.release }}

  - stage: build_micro_frontend
    displayName: "📦 Build MicroFrontend +"
    dependsOn: semantic_version_integration
    jobs:
      - template: ../ci/build/build-fronted.yml
        parameters:
          red: ${{ parameters.red }}
          apps: ${{ parameters.apps }}
          release: ${{ parameters.release }}

  - stage: deploy_micro_frontend
    displayName: "🚀 Deploy MicroFrontend"
    dependsOn: build_micro_frontend
    jobs:
      - job: jobY
        displayName: "Job Y"
        steps:
          - script: echo "Running Deployment Job Y"
