stages:
  - stage: semantic_version_microfrontend
    displayName: "🏷️ Semantic Version MicroFrontend"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          apps: ${{ parameters.apps }}
          release: ${{ parameters.release }}

  #####################################################################

  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - stage: scan_microfrontend
        displayName: "🛡️ Scan MicroFrontend"
        dependsOn: semantic_version_microfrontend
        jobs:
          - template: ../ci/tests/sonarqube-frontend.yml
            parameters:
              apps: ${{ parameters.apps }}

      - stage: build_microfrontend
        displayName: "📦 Build MicroFrontend"
        dependsOn: scan_microfrontend
        jobs:
          - template: ../ci/build/build-frontend.yml
            parameters:
              apps: ${{ parameters.apps }}

      - stage: check_build_microfrontend
        displayName: "🛡️ Check Build MicroFrontend"
        dependsOn: build_microfrontend
        condition: and(succeeded(), ne('${{ parameters.pr_id }}', '0'))
        jobs:
          - template: ../ci/pre-build/check-build-frontend.yml
            parameters:
              pr_id: ${{ parameters.pr_id }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - stage: scan_microfrontend
        displayName: "🛡️ Scan MicroFrontend"
        dependsOn: semantic_version_microfrontend
        jobs:
          - template: ../ci/tests/sonarqube-frontend.yml
            parameters:
              apps: ${{ parameters.apps }}

      - stage: build_microfrontend_develop
        displayName: "📦 Build MicroFrontend develop"
        dependsOn: scan_microfrontend
        jobs:
          - template: ../ci/build/build-frontend.yml
            parameters:
              apps: ${{ parameters.apps }}

      - stage: deploy_microfrontend_develop
        displayName: "🚀 Deploy MicroFrontend develop"
        dependsOn: build_microfrontend_develop
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              apps: ${{ parameters.apps }}
              release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      - ${{ each environment_staging in parameters.environments_staging }}:
          - stage: build_microfrontend_${{ environment_staging }}
            displayName: "📦 Build MicroFrontend ${{ environment_staging }}"
            dependsOn: semantic_version_microfrontend
            jobs:
              - template: ../ci/build/build-frontend.yml
                parameters:
                  apps: ${{ parameters.apps }}
                  environment_staging: ${{ environment_staging }}

          - stage: deploy_microfrontend_${{ environment_staging }}
            displayName: "🚀 Deploy MicroFrontend ${{ environment_staging }}"
            dependsOn: build_microfrontend_${{ environment_staging }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  apps: ${{ parameters.apps }}
                  release: ${{ parameters.release }}
                  environment_staging: ${{ environment_staging }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: build_microfrontend_${{ region }}
            displayName: "📦 Build MicroFrontend ${{ region }}"
            dependsOn: semantic_version_microfrontend
            jobs:
              - template: ../ci/build/build-frontend.yml
                parameters:
                  region: ${{ region }}
                  apps: ${{ parameters.apps }}
                  pr_id: ${{ parameters.pr_id }}

          - stage: deploy_microfrontend_${{ region }}
            displayName: "🚀 Deploy MicroFrontend ${{ region }}"
            dependsOn: build_microfrontend_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  apps: ${{ parameters.apps }}
                  release: ${{ parameters.release }}
