stages:
  - stage: semantic_version_infrastructure
    displayName: "🛡️ SonarQube Infrastructure"
    jobs:
      - template: ../ci/sonar/sonar-infrastructure.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: plan_infrastructure_${{ region }}
            displayName: "🧩 Plan Infrastructure ${{ region }}"
            dependsOn: semantic_version_infrastructure
            jobs:
              - template: ../ci/build/plan-infrastructure.yml
                parameters:
                  region: ${{ region }}

          - stage: apply_infrastructure_${{ region }}
            displayName: "🚀 Apply Infrastructure ${{ region }}"
            dependsOn: plan_infrastructure_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}

  #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - stage: plan_infrastructure
        displayName: "🧩 Plan Infrastructure"
        dependsOn: semantic_version_infrastructure
        jobs:
          - template: ../ci/build/plan-infrastructure.yml

      - ${{ if in(variables['Build.SourceBranchName'], 'develop', 'staging') }}:
          - stage: apply_infrastructure
            displayName: "🚀 Apply Infrastructure"
            dependsOn: plan_infrastructure
            jobs:
              - template: ../cd/deployment.yml
