stages:
  - stage: semantic_version_microservice
    displayName: "🏷️ Semantic Version MicroService"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  #####################################################################

  - ${{ if or(eq(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - stage: scan_microservice
        displayName: "🛡️ Scan MicroService"
        dependsOn: semantic_version_microservice
        condition: not(and(
          eq(variables['System.PullRequest.SourceBranch'],'refs/heads/staging'),
          eq(variables['System.PullRequest.TargetBranch'],'refs/heads/master')))
        jobs:
          - template: ../ci/tests/sonarqube-backend.yml
          - template: ../ci/tests/gitleaks.yml

      - stage: build_microservice
        displayName: "📦 Build MicroService"
        dependsOn: scan_microservice
        condition: always()
        jobs:
          - template: ../ci/build/build-backend.yml

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - stage: build_microservice
        displayName: "📦 Build MicroService"
        dependsOn: semantic_version_microservice
        jobs:
          - template: ../ci/build/build-backend.yml

      - ${{ each region in parameters.red }}:
          - stage: deploy_microservice_${{ region }}
            displayName: "🚀 Deploy MicroService ${{ region }}"
            dependsOn: build_microservice
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  region: ${{ region }}
                  release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - stage: scan_microservice
        displayName: "🛡️ Scan MicroService"
        dependsOn: semantic_version_microservice
        jobs:
          - template: ../ci/tests/sonarqube-backend.yml
          - template: ../ci/tests/gitleaks.yml

      - stage: build_microservice
        displayName: "📦 Build MicroService develop"
        dependsOn: scan_microservice
        jobs:
          - template: ../ci/build/build-backend.yml

      - stage: deploy_microservice_develop
        displayName: "🚀 Deploy MicroService develop"
        dependsOn: build_microservice
        jobs:
          - template: ../cd/deployment.yml
            parameters:
              release: ${{ parameters.release }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
      - stage: build_microservice
        displayName: "📦 Build MicroService"
        dependsOn: semantic_version_microservice
        jobs:
          - template: ../ci/build/build-backend.yml

      - ${{ each environment_staging in parameters.environments_staging }}:
          - stage: deploy_microservice_${{ environment_staging }}
            displayName: "🚀 Deploy MicroService ${{ environment_staging }}"
            dependsOn: build_microservice
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: ${{ parameters.release }}
                  environment_staging: ${{ environment_staging }}
