stages:
  - stage: semantic_version_electron
    displayName: "🏷️ Semantic Version Electron"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - stage: build_electron
        displayName: "📦 Build Electron"
        dependsOn: semantic_version_electron
        jobs:
          - template: ../ci/build/build-electron.yml
