stages:
  - stage: semantic_version_micro_service
    displayName: "🏷️ Semantic Version MicroService"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: ${{ parameters.release }}

  - stage: scan_micro_service
    displayName: "🛡️ Scan MicroService"
    dependsOn: semantic_version_micro_service
    jobs:
      - template: ../ci/tests/sonarqube-backend.yml
      - template: ../ci/tests/gitleaks.yml

  - stage: build_micro_service
    displayName: "📦 Build MicroService develop"
    dependsOn: scan_micro_service
    jobs:
      - template: ../ci/build/build-backend.yml

  - stage: deploy_micro_service_develop
    displayName: "🚀 Deploy MicroService develop"
    dependsOn: build_micro_service
    jobs:
      - template: ../cd/deployment.yml
        parameters:
          release: ${{ parameters.release }}
