stages:
  - stage: semantic_version_micro_fronted
    displayName: "🏷️ Semantic Version MicroFrontend"
    jobs:
      - template: ../ci/semantic-version-integration.yml
        parameters:
          release: aws-s3
          apps: ${{ parameters.apps }}

  #####################################################################

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - ${{ each region in parameters.red }}:
          - stage: build_micro_frontend_${{ region }}
            displayName: "📦 Build MicroFrontend ${{ region }}"
            dependsOn: semantic_version_micro_fronted
            jobs:
              - template: ../ci/build/build-micro-fronted.yml
                parameters:
                  region: ${{ region }}
                  apps: ${{ parameters.apps }}

          - stage: deploy_micro_frontend_${{ region }}
            displayName: "🚀 Deploy MicroFrontend ${{ region }}"
            dependsOn: build_micro_frontend_${{ region }}
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: aws-s3
                  region: ${{ region }}
                  apps: ${{ parameters.apps }}

  #####################################################################

  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - stage: build_micro_frontend
        displayName: "📦 Build MicroFrontend"
        dependsOn: semantic_version_micro_fronted
        jobs:
          - template: ../ci/build/build-micro-fronted.yml
            parameters:
              apps: ${{ parameters.apps }}

      - ${{ if in(variables['Build.SourceBranchName'], 'develop', 'staging') }}:
          - stage: deploy_micro_frontend
            displayName: "🚀 Deploy MicroFrontend"
            dependsOn: build_micro_frontend
            jobs:
              - template: ../cd/deployment.yml
                parameters:
                  release: aws-s3
                  apps: ${{ parameters.apps }}
