jobs:
  - job: "semantic_version_infrastructure"
    displayName: "🏷️ version infrastructure"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    steps:
      - script: |
          echo "Cambios"
        displayName: "🔎 Read changes infrastructure"
        condition: succeeded()
