jobs:
  - job: "semantic_version_artifact"
    displayName: "🏷️ version artifact"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - script: |
          ls -la
        displayName: "🔎 Validate Feature or Hotfix Branch is Up to Date"