jobs:
- job: 'commit_tag_version'
  dependsOn: aws_ecs
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    displayName: 'Commit and Tag Version Develop'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    displayName: 'Commit and Tag Version Staging'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'antioquia')) }}:
    displayName: 'Commit and Tag Version Master'
  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-22.04'

  strategy:
    matrix:
      ${{ each ms in parameters.apps }}:
        ${{ ms }}:
          msName: ${{ ms }}

  steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - task: NodeTool@0
      inputs:
        versionSpec: "20.x"
        checkLatest: true

    - script: |
        npm install --no-save @commitlint/cli@latest @commitlint/config-conventional@latest conventional-changelog-conventionalcommits@latest commit-and-tag-version@^12.4.4 conventional-changelog-cli@latest
        ls -la
      displayName: Install commitlint

    # - script: |
    #     cp $(System.DefaultWorkingDirectory)/apps/$(msName)/.commitlintrc.js $(System.DefaultWorkingDirectory)
    #     npx commitlint --last --verbose
    #   condition: ne(variables['Build.Reason'], 'PullRequest')
    #   displayName: Validate current commit (last commit) with commitlint
    #   continueOnError: true

    - script: |
        REPO_ID=$(curl -s -u ":$AZURE_DEVOPS_CLI_PAT" \
          "https://dev.azure.com/ux-technology/Invictus/_apis/git/repositories?api-version=5.0" \
          | jq -r '.value[] | select(.name == "$(Build.Repository.Name)").id')
        echo "id del repositorio $(Build.Repository.Name) = $REPO_ID"
        echo "##vso[task.setvariable variable=repoID]$REPO_ID"
      env:
        AZURE_DEVOPS_CLI_PAT: $(PAT-AZ)
      displayName: 'ID Repositorio'

    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'versions'
        downloadPath: '$(Pipeline.Workspace)/downloaded-versions'
      displayName: '📥 Descargar artifact de idpr'
    
    - script: |
        ls -R $(Pipeline.Workspace)/downloaded-versions/versions/idpr
        IDPR_FILE="$(Pipeline.Workspace)/downloaded-versions/versions/idpr/idpr.json"
        if [[ -f "$IDPR_FILE" ]]; then
          ID_PR=$(jq -r '.idpr' $IDPR_FILE)
          echo "🚀 IDPR version detectada: $ID_PR"
          echo "##vso[task.setvariable variable=idprversion]$ID_PR"
        else
          echo "❌ No se encontró el archivo idpr.json"
          exit 1
        fi
      displayName: '📚 Leer versiones de microservicios'

    - script: |
        echo $(idprversion)
      
    - script: |
        cd $(System.DefaultWorkingDirectory)/apps/$(msName)
        CURRENT_BRANCH=$(echo $(Build.SourceBranch))
        echo $CURRENT_BRANCH

      displayName: Tag, commit and update changeload


    