jobs:
- job: 'commit_tag_version'
  dependsOn: aws_ecs
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    displayName: 'Commit and Tag Version Develop'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    displayName: 'Commit and Tag Version Staging'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'antioquia')) }}:
    displayName: 'Commit and Tag Version Master'
  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-22.04'

  strategy:
    matrix:
      ${{ each ms in parameters.apps }}:
        ${{ ms }}:
          msName: ${{ ms }}

  steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - task: NodeTool@0
      inputs:
        versionSpec: "20.x"
        checkLatest: true

    - script: |
        npm install --no-save @commitlint/cli@latest @commitlint/config-conventional@latest conventional-changelog-conventionalcommits@latest commit-and-tag-version@latest
        ls -la
      displayName: Install commitlint

    - script: |
        cp $(System.DefaultWorkingDirectory)/apps/$(msName)/.commitlintrc.js $(System.DefaultWorkingDirectory)
        npx commitlint --last --verbose
      condition: ne(variables['Build.Reason'], 'PullRequest')
      displayName: Validate current commit (last commit) with commitlint
      continueOnError: true
      
    - script: |
        cd $(System.DefaultWorkingDirectory)/apps/$(msName)
        CURRENT_BRANCH=$(echo $(Build.SourceBranch))
        echo $CURRENT_BRANCH

        if [[ "$CURRENT_BRANCH" == refs/heads/develop ]]; then
          BUMP_OUTPUT=$(npx commit-and-tag-version --prerelease develop --dry-run )
          echo "$BUMP_OUTPUT"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | grep -oE 'to [0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+\.[0-9]+' | awk '{print $2}')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para Develop: $NEXT_VERSION"
        fi

        if [[ "$CURRENT_BRANCH" == refs/heads/staging ]]; then
          BUMP_OUTPUT=$(npx commit-and-tag-version --prerelease staging --dry-run )
          echo "$BUMP_OUTPUT"
          echo "----------------------------------------"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | grep -oE 'to [0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+\.[0-9]+' | awk '{print $2}')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para la rama de staging: $NEXT_VERSION"
        fi

        if [[ "$CURRENT_BRANCH" == refs/heads/master ]]; then
          BUMP_OUTPUT=$(npx commit-and-tag-version --dry-run )
          echo "$BUMP_OUTPUT"
          echo "----------------------------------------"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | sed -nE 's/.*to ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para la rama de master: $NEXT_VERSION"
        fi
      displayName: Tag, commit and update changeload


    