jobs:
- job: 'commit_tag_version'
  dependsOn: aws_ecs
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    displayName: 'Commit and Tag Version Develop'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    displayName: 'Commit and Tag Version Staging'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'antioquia')) }}:
    displayName: 'Commit and Tag Version Master'
  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-22.04'

  strategy:
    matrix:
      ${{ each ms in parameters.apps }}:
        ${{ ms }}:
          msName: ${{ ms }}

  steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - task: NodeTool@0
      inputs:
        versionSpec: "20.x"
        checkLatest: true

    - script: |
        npm install --no-save @commitlint/cli@latest @commitlint/config-conventional@latest conventional-changelog-conventionalcommits@latest commit-and-tag-version@^12.4.4 conventional-changelog-cli@latest
        ls -la
      displayName: Install commitlint

    # - script: |
    #     cp $(System.DefaultWorkingDirectory)/apps/$(msName)/.commitlintrc.js $(System.DefaultWorkingDirectory)
    #     npx commitlint --last --verbose
    #   condition: ne(variables['Build.Reason'], 'PullRequest')
    #   displayName: Validate current commit (last commit) with commitlint
    #   continueOnError: true

    - script: |
        REPO_ID=$(curl -s -u ":$AZURE_DEVOPS_CLI_PAT" \
          "https://dev.azure.com/ux-technology/Invictus/_apis/git/repositories?api-version=5.0" \
          | jq -r '.value[] | select(.name == "$(Build.Repository.Name)").id')
        echo "id del repositorio $(Build.Repository.Name) = $REPO_ID"
        echo "##vso[task.setvariable variable=repoID]$REPO_ID"
      env:
        AZURE_DEVOPS_CLI_PAT: $(PAT-AZ)
      displayName: 'ID Repositorio'

    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'versions'
        downloadPath: '$(Pipeline.Workspace)/downloaded-versions'
      displayName: '📥 Descargar artifact de idpr'
    
    - script: |
        ls -R $(Pipeline.Workspace)/downloaded-versions/versions/idpr
        IDPR_FILE="$(Pipeline.Workspace)/downloaded-versions/versions/idpr/idpr.json"
        if [[ -f "$IDPR_FILE" ]]; then
          ID_PR=$(jq -r '.idpr' $IDPR_FILE)
          echo "🚀 IDPR version detectada: $ID_PR"
          echo "##vso[task.setvariable variable=idprversion]$ID_PR"
        else
          echo "❌ No se encontró el archivo idpr.json"
          exit 1
        fi
      displayName: '📚 Leer ID del PR'

    - script: |
          echo "Pull Request ID recuperado: $(idprversion)"
          echo "id del repositorio $(Build.Repository.Name) = $(repoID)" 
          COMMITS=$(curl -s -u ":$AZURE_DEVOPS_CLI_PAT" \
            "https://dev.azure.com/ux-technology/Invictus/_apis/git/repositories/$(repoID)/pullRequests/$(idprversion)/commits?api-version=7.0" \
            | jq -r '.value[].comment' | grep -E 'feat:|fix:|!')
          SAFE_COMMITS=$(echo "$COMMITS" | tr '\n' '|')
          echo $SAFE_COMMITS
          echo "##vso[task.setvariable variable=filteredCommits]$SAFE_COMMITS"
      env:
        AZURE_DEVOPS_CLI_PAT: $(PAT-AZ)
      displayName: 'Detalles Commits Pull Request'
      
    - script: |
        cd $(System.DefaultWorkingDirectory)/apps/$(msName)
        CURRENT_BRANCH=$(echo $(Build.SourceBranch))
        echo $CURRENT_BRANCH

        if [[ "$CURRENT_BRANCH" == refs/heads/develop ]]; then
          raw_branch=$(Build.SourceBranch)
          clean_branch=$(echo "$raw_branch" | sed 's#refs/heads/##')

          git checkout version/$clean_branch
          git config user.name "pipeline"
          git config user.email "pipelineUX@ux.technology"

          COMMITS=$(echo "$(filteredCommits)" | tr '|' '\n')
          echo "Commits de la rama feature a develop:"
          echo $COMMITS

          IS_MAJOR=0
          IS_MINOR=0
          IS_PATCH=0

          while read -r COMMIT; do
            if [[ "$COMMIT" == *"!"* ]]; then
              IS_MAJOR=1
            elif [[ "$COMMIT" == feat:* ]]; then
              IS_MINOR=1
            elif [[ "$COMMIT" == fix:* ]]; then
              IS_PATCH=1
            fi
          done <<< "$COMMITS"

          if [[ $IS_MAJOR -eq 1 ]]; then
            RELEASE_TYPE="major"
          elif [[ $IS_MINOR -eq 1 ]]; then
            RELEASE_TYPE="minor"
          elif [[ $IS_PATCH -eq 1 ]]; then
            RELEASE_TYPE="patch"
          else
            RELEASE_TYPE="patch"  # default si no se detecta nada
          fi
          echo $RELEASE_TYPE

          BUMP_OUTPUT=$(npx commit-and-tag-version --skip.changelog --skip.tag --prerelease develop --release-as $RELEASE_TYPE)

          git push origin HEAD

          echo "$BUMP_OUTPUT"
          echo "----------------------------------------"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | grep -oE 'to [0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+\.[0-9]+' | awk '{print $2}')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para Develop: $NEXT_VERSION"
        fi

        if [[ "$CURRENT_BRANCH" == refs/heads/staging ]]; then
          raw_branch=$(Build.SourceBranch)
          clean_branch=$(echo "$raw_branch" | sed 's#refs/heads/##')

          git checkout version/$clean_branch
          git config user.name "pipeline"
          git config user.email "pipelineUX@ux.technology"

          COMMITS=$(echo "$(filteredCommits)" | tr '|' '\n')
          echo "Commits de la rama pre/staging a staging:"
          echo $COMMITS

          IS_MAJOR=0
          IS_MINOR=0
          IS_PATCH=0

          while read -r COMMIT; do
            if [[ "$COMMIT" == *"!"* ]]; then
              IS_MAJOR=1
            elif [[ "$COMMIT" == feat:* ]]; then
              IS_MINOR=1
            elif [[ "$COMMIT" == fix:* ]]; then
              IS_PATCH=1
            fi
          done <<< "$COMMITS"

          if [[ $IS_MAJOR -eq 1 ]]; then
            RELEASE_TYPE="major"
          elif [[ $IS_MINOR -eq 1 ]]; then
            RELEASE_TYPE="minor"
          elif [[ $IS_PATCH -eq 1 ]]; then
            RELEASE_TYPE="patch"
          else
            RELEASE_TYPE="patch"  # default si no se detecta nada
          fi
          echo $RELEASE_TYPE

          BUMP_OUTPUT=$(npx commit-and-tag-version --skip.changelog --skip.tag --prerelease qa --release-as $RELEASE_TYPE)
          
          git push origin HEAD

          echo "$BUMP_OUTPUT"
          echo "----------------------------------------"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | grep -oE 'to [0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+\.[0-9]+' | awk '{print $2}')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para Staging: $NEXT_VERSION"
        fi

        if [[ "$CURRENT_BRANCH" == refs/heads/master ]]; then
          raw_branch=$(Build.SourceBranch)
          clean_branch=$(echo "$raw_branch" | sed 's#refs/heads/##')

          git checkout version/$clean_branch
          git config user.name "pipeline"
          git config user.email "pipelineUX@ux.technology"

          COMMITS=$(echo "$(filteredCommits)" | tr '|' '\n')
          echo "Commits de la rama staging a master:"
          echo $COMMITS

          IS_MAJOR=0
          IS_MINOR=0
          IS_PATCH=0

          while read -r COMMIT; do
            if [[ "$COMMIT" == *"!"* ]]; then
              IS_MAJOR=1
            elif [[ "$COMMIT" == feat:* ]]; then
              IS_MINOR=1
            elif [[ "$COMMIT" == fix:* ]]; then
              IS_PATCH=1
            fi
          done <<< "$COMMITS"

          if [[ $IS_MAJOR -eq 1 ]]; then
            RELEASE_TYPE="major"
          elif [[ $IS_MINOR -eq 1 ]]; then
            RELEASE_TYPE="minor"
          elif [[ $IS_PATCH -eq 1 ]]; then
            RELEASE_TYPE="patch"
          else
            RELEASE_TYPE="patch"  # default si no se detecta nada
          fi
          echo $RELEASE_TYPE

          BUMP_OUTPUT=$(npx commit-and-tag-version --skip.changelog --skip.tag --release-as $RELEASE_TYPE)
          
          git push origin HEAD

          echo "$BUMP_OUTPUT"
          echo "----------------------------------------"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | grep -oE 'to [0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+\.[0-9]+' | awk '{print $2}')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para master: $NEXT_VERSION"
        fi
      displayName: Tag, commit and update changeload


    