
jobs:
- job: 'semantic_version'
  displayName: 'Semantic Version'
  pool:
    name: 'Azure Pipelines'
    VmImage: ubuntu-22.04

  strategy:
      matrix:
        ${{ each ms in parameters.apps }}:
          ${{ ms }}:
            msName: ${{ ms }}
  steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - task: NodeTool@0
      inputs:
        versionSpec: "20.x"
        checkLatest: true

    - script: |
        npm install conventional-changelog-conventionalcommits
        npm install @commitlint@latest @commitlint/config-conventional@latest
      displayName: Install commitlint

    - script: |
        cp $(System.DefaultWorkingDirectory)/apps/$(msName)/.commitlintrc.json $(System.DefaultWorkingDirectory)
        npx commitlint --last --verbose 
      condition: ne(variables['Build.Reason'], 'PullRequest')
      displayName: Validate current commit (last commit) with commitlint

    