parameters:
  apps: []

jobs:
- job: 'semantic_version'
  displayName: 'Semantic Version'
  pool:
    name: 'Azure Pipelines'
    VmImage: ubuntu-22.04
  steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    # - script: |
    #     echo $APPS_LIST
    #     CHANGED_MS_LIST=$(echo "$APPS_LIST" | xargs -n1 | jq -R . | jq -s .)
    #     echo $CHANGED_MS_LIST
    #     for ms in $(echo "$CHANGED_MS_LIST" | jq -r '.[]'); do
    #       echo "Procesando microservicio: $ms"
    #       VERSION=$(jq -r '.version' "$(Build.SourcesDirectory)/apps/$ms/package.json")
    #       echo "Versión de $ms: $VERSION"
    #       echo "##vso[task.setvariable variable=${ms}_version]$VERSION"
    #     done
    #   displayName: "Obtener versiones de los MS cambiados"
    #   env:
    #     APPS_LIST: ${{ join(' ', parameters.apps) }}

    - script: |
        echo $APPS_LIST
        CHANGED_MS_LIST=$(echo "$APPS_LIST" | xargs -n1 | jq -R . | jq -s .)
        echo $CHANGED_MS_LIST
        
        CURRENT_BRANCH=$(echo $(Build.SourceBranch))
        echo "Branch actual: $CURRENT_BRANCH"

        git fetch origin master
        MASTER_BRANCH="origin/master"


        if [[ "$CURRENT_BRANCH" == refs/heads/feature/* ]]; then
          COMPARE_BRANCH="develop"
          APPLY_BUMP=false
        fi

        echo "Se comparará contra: $COMPARE_BRANCH"
        git fetch origin $COMPARE_BRANCH

        bump_version() {
          local version=$1
          local bump=$2
          IFS='.' read -r major minor patch <<< "$version"
          case "$bump" in
            major) echo "$((major + 1)).0.0" ;;
            minor) echo "$major.$((minor + 1)).0" ;;
            patch) echo "$major.$minor.$((patch + 1))" ;;
            *) echo "$version" ;;
          esac
        }




        for ms in $(echo "$CHANGED_MS_LIST" | jq -r '.[]'); do
          echo "Procesando MS: $ms"
          SERVICE_PATH="$(Build.SourcesDirectory)/apps/$ms"
          PACKAGE_JSON="$SERVICE_PATH/package.json"
          CURRENT_VERSION=$(jq -r '.version' "$PACKAGE_JSON")


          LOG=$(git log origin/$COMPARE_BRANCH..HEAD --pretty=%B -- apps/$ms) 

          if echo "$LOG" | grep -q "#major"; then
            bump_type="major"
          elif echo "$LOG" | grep -q "#minor"; then
            bump_type="minor"
          elif echo "$LOG" | grep -q "#patch"; then
            bump_type="patch"
          else
            bump_type=""
          fi
          
          NEW_VERSION=$(bump_version "$CURRENT_VERSION" "$bump_type")

          echo "🧪 [Dry Run] $ms tendría bump $bump_type: $CURRENT_VERSION → $NEW_VERSION"

          # echo "Versión actual: $VERSION"
        done
        
      displayName: "Obtener versiones de los MS cambiados"
      env:
        APPS_LIST: ${{ join(' ', parameters.apps) }}