
jobs:
- job: 'semantic_version'
  displayName: 'Semantic Version'
  pool:
    name: 'Azure Pipelines'
    VmImage: ubuntu-22.04

  strategy:
      matrix:
        ${{ each ms in parameters.apps }}:
          ${{ ms }}:
            msName: ${{ ms }}
  steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - task: NodeTool@0
      inputs:
        versionSpec: "20.x"
        checkLatest: true

    - script: |
        npm install --no-save @commitlint/cli@latest @commitlint/config-conventional@latest conventional-changelog-conventionalcommits@latest commit-and-tag-version@latest
        ls -la
      displayName: Install commitlint

    - script: |
        cp $(System.DefaultWorkingDirectory)/apps/$(msName)/.commitlintrc.js $(System.DefaultWorkingDirectory)
        # npx commitlint --from origin/develop --to HEAD --verbose
        npx commitlint --last --verbose
      condition: ne(variables['Build.Reason'], 'PullRequest')
      displayName: Validate current commit (last commit) with commitlint
      continueOnError: true

    - script: |
        cd $(System.DefaultWorkingDirectory)/apps/$(msName)
        CURRENT_BRANCH=$(echo $(Build.SourceBranch))
        echo $CURRENT_BRANCH
        if [[ "$CURRENT_BRANCH" == refs/heads/feature/* ]]; then
          # BUMP_OUTPUT=$(npx commit-and-tag-version --dry-run --skip.commit --skip.tag)
          BUMP_OUTPUT=$(npx commit-and-tag-version -- --prerelease feature --skip.changelog)
          echo "$BUMP_OUTPUT"
          echo "----------------------------------------"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*to ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para la rama develop: $NEXT_VERSION"
        fi

        if [[ "$CURRENT_BRANCH" == refs/heads/develop ]]; then
          BUMP_OUTPUT=$(npx commit-and-tag-version -- --prerelease develop)
          echo "$BUMP_OUTPUT"
          echo "----------------------------------------"
          
          CURRENT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*from ([0-9]+\.[0-9]+\.[0-9]+) to.*/\1/')
          NEXT_VERSION=$(echo "$BUMP_OUTPUT" | grep "bumping version" | sed -E 's/.*to ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')

          echo "📌 Versión actual detectada: $CURRENT_VERSION"
          echo "🚀 Próxima versión para la rama develop: $NEXT_VERSION"
        fi

        
      displayName: Detect next version

    