jobs:
  - job: "semantic_version"
    displayName: "Semantic Version"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    strategy:
      matrix:
        ${{ each pair in parameters.apps }}:
          ${{ pair.Key }}:
            msName: ${{ pair.Key }}
            msVersion: ${{ pair.Value }}

    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true


      - script: |
          echo "Procesando $(msName) versión $(msVersion)"

          mkdir -p $(Build.ArtifactStagingDirectory)/$(msName)
          touch $(Build.ArtifactStagingDirectory)/$(msName)/version.json
          echo "{ \"ms\": \"$(msName)\", \"version\": \"$(msVersion)\" }" > $(Build.ArtifactStagingDirectory)/$(msName)/version.json
        displayName: "Create version file for $(msName)"
