jobs:
- job: 'semantic_version'
  displayName: 'Semantic Version'
  pool:
    name: 'Azure Pipelines'
    VmImage: ubuntu-22.04
  steps:
    - checkout: self
      fetchDepth: 0
  
    - script: |
        cd $(Build.SourcesDirectory)/apps
        CHANGED_MS=$(git diff --name-only HEAD~1 HEAD | grep "^apps/" | cut -d '/' -f2 | sort | uniq | xargs)
        echo $CHANGED_MS
        echo "##vso[task.setvariable variable=changedMs]$CHANGED_MS"
        echo "Microservicios detectados: $CHANGED_MS"
      name: DetectChangedMS

    - script: |
        echo $(changedMs)
        CHANGED_MS_LIST=$(echo "$(changedMs)" | xargs -n1 | jq -R . | jq -s .)
        echo $CHANGED_MS_LIST
      displayName: "Obtener versiones de los MS cambiados"
            
