jobs:
  - deployment: WaitForApproval
    displayName: "Esperar aprobación"
    pool:
      name: Azure Pipelines
      vmImage: "ubuntu-22.04"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      environment: "Deploy Develop"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
      environment: "Deploy Staging"
    ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
      displayName: "Deploy Master ${{ parameters.red }}"
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Aprobación recibida. Iniciando despliegues..."

  - job: "aws_s3"
    dependsOn: WaitForApproval
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      displayName: "AWS S3 Develop"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
      displayName: "AWS S3 Staging"
    ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
      displayName: "AWS S3 Master ${{ parameters.red }}"
    pool:
      name: Azure Pipelines
      vmImage: "ubuntu-22.04"

    strategy:
      matrix:
        ${{ each ms in parameters.apps }}:
          ${{ ms }}:
            msName: ${{ ms }}

    steps:
      - script: |
          echo "Original msName: $(msName)"
        displayName: "deploy $(msName)"

      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: "versions"
          downloadPath: "$(Pipeline.Workspace)/downloaded-versions"
        displayName: "📥 Download Version Artifact"

      - script: |
          ls -R $(Pipeline.Workspace)/downloaded-versions/versions/$(msName)
          VERSION_FILE="$(Pipeline.Workspace)/downloaded-versions/versions/$(msName)/version.json"
          if [[ -f "$VERSION_FILE" ]]; then
            VERSION=$(jq -r '.version' $VERSION_FILE)
            echo "🚀 Versión detectada para $(msName): $VERSION"
            echo "##vso[task.setvariable variable=msVersion]$VERSION"
          else
            echo "❌ No se encontró archivo de versión para $(msName)"
            exit 1
          fi
        displayName: "📖 Read Microservice Versions"

      - script: |
          ENV_VAR_NAME=$(echo "$(msName)" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
          ENV_VAR_NAME=CLOUDFRONT_ID_$ENV_VAR_NAME
          echo $ENV_VAR_NAME

          CLOUDFRONT_ID_VALUE="${!ENV_VAR_NAME}"
          echo $CLOUDFRONT_ID_VALUE

          echo "##vso[task.setvariable variable=CLOUDFRONT_ID]$CLOUDFRONT_ID_VALUE"
        displayName: "Name Var Cloudfront"

      - script: |
          aws cloudfront get-distribution-config --id $(CLOUDFRONT_ID) --region $(AWS_DEFAULT_REGION) > $(CLOUDFRONT_ID).json
          cat $(CLOUDFRONT_ID).json
        displayName: "Get Distribution"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

      - script: |
          echo "version a actualizar: $(msVersion)"
          jq --arg v "/$(msVersion)" '.DistributionConfig.Origins.Items[0].OriginPath = $v' "$(CLOUDFRONT_ID).json" > "temp-$(CLOUDFRONT_ID).json"
          cat temp-$(CLOUDFRONT_ID).json
        displayName: "Insert New Version"

      - script: |
          ETAG=$(jq -r '.ETag' $(CLOUDFRONT_ID).json)
          echo tag: "$ETAG"
          jq '.DistributionConfig' "temp-$(CLOUDFRONT_ID).json" > "updated-$(CLOUDFRONT_ID).json"
          cat updated-$(CLOUDFRONT_ID).json
          aws cloudfront update-distribution --id $(CLOUDFRONT_ID) --region $AWS_DEFAULT_REGION --if-match "$ETAG" --distribution-config file://updated-$(CLOUDFRONT_ID).json
        displayName: "Update Distribute"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          
      - script: |
          echo "⏳ Esperando a que la distribución $(CLOUDFRONT_ID) se propague..."

          while true; do
            STATUS=$(aws cloudfront get-distribution --id $(CLOUDFRONT_ID) --region $AWS_DEFAULT_REGION | jq -r '.Distribution.Status')
            echo "🔄 Estado actual: $STATUS"
            if [ "$STATUS" == "Deployed" ]; then
              echo "✅ Distribución propagada correctamente."
              break
            fi
            sleep 10
          done
        displayName: "Waiting for CloudFront propagation"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

      - script: |
          echo "Creando invalidación de CloudFront..."
          RESULT=$(aws cloudfront create-invalidation --distribution-id $(CLOUDFRONT_ID) --paths '/*')
          echo "$RESULT"

          INVALIDATION=$(echo "$RESULT" | jq -r '.Invalidation.Id')
          echo "ID de invalidación: $INVALIDATION"
          echo "##vso[task.setvariable variable=INVALIDATION_ID]$INVALIDATION"
          
        displayName: "Create Invalidation"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)

      - script: |
          echo "⏳ Esperando que CloudFront complete la invalidación..."
          echo "🆔 ID de invalidación: $(INVALIDATION_ID)"

          while true; do
            STATUS=$(aws cloudfront get-invalidation --distribution-id $(CLOUDFRONT_ID) --id "$INVALIDATION_ID" --region $AWS_DEFAULT_REGION | jq -r '.Invalidation.Status')
            echo "🔄 Estado actual de la invalidación: $STATUS"
            if [ "$STATUS" == "Completed" ]; then
              echo "✅ Invalidation completada con éxito."
              break
            fi
            sleep 10
          done
        displayName: "Waiting for invalidation Caché"
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
