jobs:
- deployment: WaitForApproval
  displayName: 'Esperar aprobación'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    environment: 'Deploy develop' 
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    environment: 'Deploy staging' 
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'antioquia')) }}:
    environment: 'Deploy master antioquia'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'cap')) }}:
    environment: 'Deploy master cap'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'tolima')) }}:
    environment: 'Deploy master tolima'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'huila')) }}:
    environment: 'Deploy master huila'
  strategy:
    runOnce:
      deploy:
        steps:
          - script: echo "Aprobación recibida. Iniciando despliegues..."

- job: 'aws_ecs'
  dependsOn: WaitForApproval
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    displayName: 'AWS ECS Develop'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    displayName: 'AWS ECS Staging'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'antioquia')) }}:
    displayName: 'AWS ECS master Antioquia'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'cap')) }}:
    displayName: 'AWS ECS master cap'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'tolima')) }}:
    displayName: 'AWS ECS master tolima'
  ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.red, 'huila')) }}:
    displayName: 'AWS ECS master huila'
  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-22.04'

  strategy:
    matrix:
      ${{ each ms in parameters.apps }}:
        ${{ ms }}:
          msName: ${{ ms }}

  steps:

    - script: |
          echo "Original msName: $(msName)"
          cleanName=$(echo $(msName) | sed 's/microservice-//')
          echo "Nombre limpio: $cleanName"
          echo "##vso[task.setvariable variable=cleanMsName]$cleanName"
      displayName: "deploy $(msName)"

    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'versions'
        downloadPath: '$(Pipeline.Workspace)/downloaded-versions'
      displayName: '📥 Descargar artifact de versiones'
        
    - script: |
        ls -R $(Pipeline.Workspace)/downloaded-versions/versions/$(msName)
        VERSION_FILE="$(Pipeline.Workspace)/downloaded-versions/versions/$(msName)/version.json"
        if [[ -f "$VERSION_FILE" ]]; then
          VERSION=$(jq -r '.version' $VERSION_FILE)
          echo "🚀 Versión detectada para $(msName): $VERSION"
          echo "##vso[task.setvariable variable=msVersion]$VERSION"
        else
          echo "❌ No se encontró archivo de versión para $(msName)"
          exit 1
        fi
      displayName: '📚 Leer versiones de microservicios'

    - script: |
        echo $(msVersion)

    - script: |
        export AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY
        export AWS_REGION

        echo "Obteniendo task definition..."
        arn=$(aws ecs describe-services \
          --cluster $CLUSTER \
          --services $SERVICES \
          --query 'services[0].taskDefinition' \
          --output text \
          --region $(AWS_DEFAULT_REGION))
          
        echo "TaskDef ARN: $arn"
        echo "##vso[task.setvariable variable=taskDefinitionArn]$arn"
      displayName: "Obtener task definition ARN"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    - script: |
        echo "Obteniendo family de task definition..."
        ARN='$(taskDefinitionArn)'
        echo $ARN
        
        FAMILY=$(echo $ARN | cut -d'/' -f2 | cut -d':' -f1)
        echo "##vso[task.setvariable variable=taskFamily]$FAMILY"
      displayName: 'Extraer family desde ARN'

    - script: |
        export AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY
        export AWS_REGION

        echo "Obteniendo definición actual..."
        aws ecs describe-task-definition \
          --task-definition $(taskDefinitionArn) \
          --query 'taskDefinition' \
          > taskdef.json
        cat taskdef.json
      displayName: "Obtener definición de la task actual"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    - script: |
        newTag="$(msVersion)"

        jq --arg newTag "$newTag" '
          .containerDefinitions |= map(
            .image |= (split(":")[0] + ":" + $newTag)
          )
        ' taskdef.json > new-taskdef-$(cleanMsName).json

        echo "Imagen actualizada con nuevo tag: $newTag"
        cat new-taskdef-$(cleanMsName).json
      displayName: "Cambio de tag Images task"

    - script: |
        jq '{
          family,
          taskRoleArn,
          executionRoleArn,
          networkMode,
          containerDefinitions,
          volumes,
          placementConstraints,
          requiresCompatibilities,
          cpu,
          memory,
          tags,
          pidMode,
          ipcMode,
          proxyConfiguration,
          inferenceAccelerators,
          ephemeralStorage,
          runtimePlatform
        } | with_entries(select(.value != null))' new-taskdef-$(cleanMsName).json > new-taskdef-$(cleanMsName)-ecs.json

        cat new-taskdef-$(cleanMsName)-ecs.json

      displayName: "Delete attributes"



    # - script: |
    #     export AWS_ACCESS_KEY_ID
    #     export AWS_SECRET_ACCESS_KEY
    #     export AWS_REGION

    #     output=$(aws ecs register-task-definition \
    #     --cli-input-json file://new-taskdef-$(cleanMsName)-ecs.json \
    #     --region $AWS_DEFAULT_REGION)

    #     arn=$(echo $output | jq -r '.taskDefinition.taskDefinitionArn')
    
    #     echo "Nueva Task Definition ARN: $arn"
        
    #     echo "##vso[task.setvariable variable=taskDefinitionArnNew]$arn"

    #   displayName: "Registrar nueva task definition"
    #   env:
    #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    # - script: |
    #     export AWS_ACCESS_KEY_ID
    #     export AWS_SECRET_ACCESS_KEY
    #     export AWS_REGION

    #     echo $(taskDefinitionArnNew)

    #     aws ecs update-service \
    #       --cluster $CLUSTER \
    #       --service $SERVICES \
    #       --task-definition $(taskDefinitionArnNew) \
    #       --region $AWS_DEFAULT_REGION
    #   displayName: "Actualizar servicio con nueva task definition"
    #   env:
    #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)