jobs:
  - job: "checkov_infrastructure"
    displayName: "🛡️ checkov"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-iac.yml

    steps:
      - task: Bash@3
        displayName: "🔎 Checkov Scan"
        inputs:
          targetType: "inline"
          script: |
            docker run --rm \
              -v $(System.DefaultWorkingDirectory):/workdir \
              bridgecrew/checkov:latest \
              -d /workdir \
              --framework terraform \
              --hard-fail-on HIGH,CRITICAL \
              --skip-check CKV_AWS_59 \
              --skip-check CKV_AWS_120 \
              --skip-check CKV_AWS_310 \
              --skip-check CKV_AWS_86 \
              --skip-check CKV_AWS_68 \
              --skip-check CKV_AWS_374 \
              --skip-check CKV_AWS_108 \
              --skip-check CKV_AWS_287 \
              --skip-check CKV_AWS_355 \
              --skip-check CKV_AWS_290 \
              --skip-check CKV_AWS_8 \
              --skip-check CKV_AWS_126 \
              --skip-check CKV_AWS_79 \
              --skip-check CKV_AWS_65 \
              --skip-check CKV_AWS_336 \
              --skip-check CKV_AWS_158 \
              --skip-check CKV_AWS_31 \
              --skip-check CKV_AWS_191 \
              --skip-check CKV_AWS_61 \
              --skip-check CKV_AWS_273 \
              --skip-check CKV_AWS_43 \
              --skip-check CKV_AWS_185 \
              --skip-check CKV_AWS_91 \
              --skip-check CKV_AWS_324 \
              --quiet
