jobs:
  - job: "sonarqube_infrastructure"
    displayName: "🛡️ sonarqube"
    pool:
      name: "Azure Pipelines"
      vmImage: ubuntu-latest

    variables:
      - template: ../../variables/groups-transversal-variables-iac.yml

    steps:
      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            set -e
            if [[ "$(Build.Reason)" == "PullRequest" ]]; then
              BRANCH="$(System.PullRequest.SourceBranch)"
            else
              BRANCH="$(Build.SourceBranch)"
            fi

            BRANCH="${BRANCH#refs/heads/}"
            REGEX='^(feature/R-[0-9]+-[a-zA-Z0-9._-]+|hotfix/I-[0-9]+-[a-zA-Z0-9._-]+|develop|staging|master)$'
            echo "Validando rama: $BRANCH"

            if [[ ! "$BRANCH" =~ $REGEX ]]; then
              echo -e "\n##vso[task.logissue type=error]⚠️ El nombre de la rama '$BRANCH' no cumple el estándar."
              echo "##vso[task.logissue type=error]  feature/R-0000-nombre-rama"
              echo "##vso[task.logissue type=error]  hotfix/I-0000-nombre-rama"
              exit 99
            fi
            echo "✅ Nombre de la rama es valido"
        displayName: "🔎 Validate Branch Name"
        condition: succeeded()

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: "17"
          jdkArchitectureOption: "x64"
          jdkSourceOption: "PreInstalled"
        displayName: "🔧 Install JDK 17"
        condition: succeeded()

      - task: SonarQubePrepare@7
        inputs:
          SonarQube: "SonarQubeConection"
          scannerMode: "CLI"
          configMode: "manual"
          cliProjectKey: "$(Build.Repository.Name)"
          cliProjectName: "$(Build.Repository.Name)"
          cliSources: "$(System.DefaultWorkingDirectory)"
          extraProperties: |
            sonar.sources=iac-template-terraform
            sonar.inclusions=**/*.tf,**/*.tfvars,**/*.hcl
            sonar.terraform.file.suffixes=tf,tfvars,hcl
            sonar.exclusions=**/.terraform/**,**/.terragrunt-cache/**,**/terraform.tfstate*,**/*tfplan*,**/terragrunt.hcl.lock*,**/*.lock.hcl,pipeline/**
        displayName: "⚙️ Prepare SonarQube Analysis"
        condition: succeeded()

      - task: SonarQubeAnalyze@7
        displayName: "📡 Run Sonar Analysis"
        condition: succeeded()

      - task: SonarQubePublish@7
        inputs:
          pollingTimeoutSec: 400
        displayName: "📤 Publish Static Code Analysis Results"
        condition: succeeded()

      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            set -e
            echo "🔎 Validando Quality Gates..."

            PROJECT_KEY="$(Build.Repository.Name)"
            BRANCH_NAME="${BUILD_SOURCEBRANCH#refs/heads/}"

            if [[ -n "$SYSTEM_PULLREQUEST_PULLREQUESTID" ]]; then
              query="pullRequest=$SYSTEM_PULLREQUEST_PULLREQUESTID"
              dashboard_url="$SONAR_HOST_URL/dashboard?id=$PROJECT_KEY&pullRequest=$SYSTEM_PULLREQUEST_PULLREQUESTID"
            else
              query="branch=$BRANCH_NAME"
              dashboard_url="$SONAR_HOST_URL/dashboard?id=$PROJECT_KEY&branch=$BRANCH_NAME"
            fi

            # Obtener estado del Quality Gate
            status=$(curl -sf -u "$SONAR_TOKEN:" \
              "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$PROJECT_KEY&$query")

            # Obtener nombre del Quality Gate
            quality_gate_response=$(curl -sf -u "$SONAR_TOKEN:" \
              "$SONAR_HOST_URL/api/qualitygates/get_by_project?project=$PROJECT_KEY")

            status_code=$(echo "$status" | jq -r '.projectStatus.status')
            quality_gate=$(echo "$quality_gate_response" | jq -r '.qualityGate.name // "N/A"')

            echo ""
            echo "📦 Proyecto:         $PROJECT_KEY"
            echo "🌿 Rama:             $BRANCH_NAME"

            if [[ -n "$SYSTEM_PULLREQUEST_PULLREQUESTID" ]]; then
              echo "🔀 Pull Request:     $SYSTEM_PULLREQUEST_PULLREQUESTID"
            fi

            echo "🛡️ Quality Gate:     $quality_gate"
            echo "🟢 Estado:           $status_code"
            echo ""

            echo "##[command]🌐 URL: $dashboard_url"

            if [[ "$status_code" != "OK" ]]; then
              echo -e "\n##vso[task.logissue type=error]⚠️ El proyecto no cumple con los Qualitys."
              exit 99
            fi

            echo "✅ El proyecto cumple con los Qualitys."
        displayName: "🛡️ Quality Gate Check: $(Build.Repository.Name)"
        condition: succeeded()
        continueOnError: true
        env:
          SONAR_TOKEN: $(SONAR_TOKEN)
          SONAR_HOST_URL: $(SONAR_HOST_URL)
