stages:
- stage: 'artifacts_managment'
  displayName: 'Artifacts Managment'
  dependsOn:
    - 'build_developmet'
  condition: in(dependencies.build_developmet.result, 'Succeeded', 'SucceededWithIssues')

  variables:
  - template: ../variables/groups-transversal-variables.yml

  jobs:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop')}}:
    - job: 'publish_image_dev'
      displayName: 'Publish Docker Image Development Environment'
      pool:
        name: 'Azure Pipelines'
        VmImage: 'ubuntu-22.04'
      steps:
        - script: |
            echo "build dev docker images"

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    - job: 'publish_image_qa'
      displayName: 'Publish Docker Image Staging Environment'
      pool:
        name: 'Azure Pipelines'
        VmImage: 'ubuntu-22.04'
      steps:
        - script: |
            echo "build qa docker images"

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - job: 'publish_image_pnd'
      displayName: 'Publish Docker Image master Environment'
      pool:
        name: 'Azure Pipelines'
        VmImage: 'ubuntu-22.04'
      steps:
        - script: |
            echo "build pdn docker images"

