stages:
- stage: 'artifacts_managment'
  displayName: 'Artifacts Managment'
  # dependsOn:
  #   - 'build_developmet'
  # condition: in(dependencies.build_developmet.result, 'Succeeded', 'SucceededWithIssues')

  variables:
  - template: ../variables/groups-transversal-variables.yml

  jobs:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop')}}:
    - job: 'publish_image_dev'
      displayName: 'Publish Docker Image Development Environment'
      pool:
        name: 'Azure Pipelines'
        VmImage: 'ubuntu-22.04'

      parameters:
        apps: ${{ parameters.apps }}

      strategy:
      matrix:
        ${{ each ms in parameters.apps }}:
          ${{ ms }}:
            msName: ${{ ms }}

      steps:
        - checkout: self

        - checkout: git://DevOps-templates-UX/pipelines-templates@feature/Inicio-templates
          fetchDepth: 1

        - script: |
            echo "build dev docker images"
            ls -la 
            cd Pruebas-consumir-template/apps/$(msName)
            ls -la
        
        - script: |
            echo "Logging in to ECR..."
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
            docker login --username AWS --password-stdin $ACCOUNT_ID_DEPLOY.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          displayName: 'Login to AWS ECR'
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
        
        - task: Docker@2
          displayName: 'Build image'
          inputs:
            command: 'build'
            repository: 'pruebas-pipeline-dev'
            Dockerfile: 'pipelines-templates/pipeline/docker/Dockerfile'
            tags: $(Build.BuildNumber)

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    - job: 'publish_image_qa'
      displayName: 'Publish Docker Image Staging Environment'
      pool:
        name: 'Azure Pipelines'
        VmImage: 'ubuntu-22.04'
      steps:
        - script: |
            echo "build qa docker images"

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - job: 'publish_image_pnd'
      displayName: 'Publish Docker Image master Environment'
      pool:
        name: 'Azure Pipelines'
        VmImage: 'ubuntu-22.04'
      steps:
        - script: |
            echo "build pdn docker images"

