parameters:
  - name: msName
    type: string
  - name: clusters
    type: object

stages:
  - stage: Deploy_${{ parameters.msName }}
    displayName: Desplegar ${{ parameters.msName }}
    jobs:
      - job: DeployMatrix
        displayName: "Deploy ${{ parameters.msName }} en clusters"
        strategy:
          matrix:
            dev:
              clusterName: dev
            qa:
              clusterName: qa
            prod:
              clusterName: prod
        steps:
          - script: |
              echo "Desplegando ${{ parameters.msName }} en ${{ matrix.clusterName }}"

