stages:
- stage: 'ecosystem_integration_qa'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    displayName: 'Deploy Integration Development'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
    displayName: 'Deploy Integration Staging' 
  ${{ if or(in(variables['Build.SourceBranch'], 'refs/heads/master' ), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    displayName: 'Deploy Integration Master'
  
  dependsOn: 
    - 'artifacts_managment'
  condition:
      in(dependencies.artifacts_managment.result, 'Succeeded', 'SucceededWithIssues')

  pool:
    name: 'Azure Pipelines'
    VmImage: Ubuntu-20.04

  variables:
  - template: ../variables/groups-transversal-variables.yml

  jobs:
  - ${{ if in(parameters.typerelease, 'aws') }}:
    # - template: jobs/aws-ecs-jobs.yml
    #   parameters:
    #     language: ${{ parameters.language }}
    #     typerelease: ${{ parameters.typerelease }}
    #     apps: ${{ parameters.apps }}

    - template: jobs/aws-ecs-jobs-QA.yml
      parameters:
        language: ${{ parameters.language }}
        typerelease: ${{ parameters.typerelease }}
        apps: ${{ parameters.apps }}

