stages:
  - stage: "deploy_integration_${{ parameters.redes }}"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      displayName: "Deploy Integration Development"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
      displayName: "Deploy Integration Staging"
    ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.redes, 'antioquia')) }}:
      displayName: "Deploy Integration Master Antioquia"
    ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.redes, 'cap')) }}:
      displayName: "Deploy Integration Master Cap"
    ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.redes, 'tolima')) }}:
      displayName: "Deploy Integration Master Tolima"
    ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.redes, 'huila')) }}:
      displayName: "Deploy Integration Master Huila"
    ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.redes, 'cauca')) }}:
      displayName: "Deploy Integration Master Cauca"

    ${{ if eq(parameters.language, 'nodejs') }}:
      dependsOn:
        - "artifacts_managment"
      condition: in(dependencies.artifacts_managment.result, 'Succeeded', 'SucceededWithIssues')

    ${{ if eq(parameters.language, 'nodejsFront') }}:
      dependsOn:
        - "build_developmet_${{ parameters.redes }}"
      condition: in(dependencies.build_developmet_${{ parameters.redes }}.result, 'Succeeded', 'SucceededWithIssues')

    pool:
      name: "Azure Pipelines"
      VmImage: Ubuntu-20.04

    variables:
      - template: ../variables/groups-transversal-variables.yml
        parameters:
          redes: ${{ parameters.redes }}

    jobs:
      - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/staging', 'refs/heads/master')) }}:
          - ${{ if in(parameters.release, 'aws-ecs') }}:
              - template: jobs/aws-ecs-jobs.yml
                parameters:
                  language: ${{ parameters.language }}
                  release: ${{ parameters.release }}
                  apps: ${{ parameters.apps }}
                  redes: ${{ parameters.redes }}

      - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/staging', 'refs/heads/master')) }}:
          - ${{ if in(parameters.release, 'aws-s3') }}:
              - template: jobs/aws-s3-jobs.yml
                parameters:
                  language: ${{ parameters.language }}
                  release: ${{ parameters.release }}
                  apps: ${{ parameters.apps }}
                  redes: ${{ parameters.redes }}

      - ${{ if and(or(in(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')), eq(parameters.redes, 'antioquia')) }}:
          - template: ../general/commit-tag-changeload.yml
            parameters:
              apps: ${{ parameters.apps }}
              redes: ${{ parameters.redes }}
              release: ${{ parameters.release }}
