stages:
  - stage: "deploy_integration_${{ parameters.red }}"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      displayName: "🚀 Deploy Integration Develop"
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
      displayName: "🚀 Deploy Integration Staging"
    ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
      displayName: "🚀 Deploy Integration Master ${{ parameters.red }}"

    ${{ if eq(parameters.release, 'ecs-redes') }}:
      dependsOn:
        - "semantic_version_integration"
      condition: in(dependencies.semantic_version_integration.result, 'Succeeded', 'SucceededWithIssues')

    pool:
      name: "Azure Pipelines"
      VmImage: Ubuntu-20.04

    variables:
      - template: ../variables/groups-transversal-variables-ecs-redes.yml
        parameters:
          red: ${{ parameters.red }}

    jobs:
      - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), in(variables['Build.SourceBranch'], 'refs/heads/develop', 'refs/heads/staging', 'refs/heads/master')) }}:
          - ${{ if in(parameters.release, 'ecs-redes') }}:
              - template: jobs/aws-ecs-jobs-old.yml
                parameters:
                  release: ${{ parameters.release }}
                  apps: ${{ parameters.apps }}
                  red: ${{ parameters.red }}

