parameters:
  - name: msName
    type: string

stages:
  - stage: Deploy_${{ replace(parameters.msName, '-', '_') }}
    displayName: Desplegar ${{ parameters.msName }}
    jobs:
      - deployment: DeployMatrix
        displayName: "Deploy ${{ parameters.msName }} en clusters"
        dependsOn: []
        environment: 'Deploy ${{ parameters.msName }}'
        pool:
          name: 'Azure Pipelines'
          VmImage: Ubuntu-20.04
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Desplegando ${{ parameters.msName }}"

