jobs:
  - job: "sonarqube_infrastructure"
    displayName: "🛡️ sonarqube"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-iac.yml

    steps:
      - task: JavaToolInstaller@0
        displayName: "🔧 Install JDK 17"
        inputs:
          versionSpec: "17"
          jdkArchitectureOption: "x64"
          jdkSourceOption: "PreInstalled"
        condition: succeeded()

      - task: SonarQubePrepare@7
        displayName: "⚙️ Prepare SonarQube Analysis"
        inputs:
          SonarQube: "SonarQubeConection"
          scannerMode: "CLI"
          configMode: "manual"
          cliProjectKey: "$(Build.Repository.Name)"
          cliProjectName: "$(Build.Repository.Name)"
          cliSources: "$(System.DefaultWorkingDirectory)"
          extraProperties: |
            sonar.sources=iac-template-terraform
            sonar.inclusions=**/*.tf,**/*.tfvars,**/*.hcl
            sonar.terraform.file.suffixes=tf,tfvars,hcl
            sonar.exclusions=**/.terraform/**,**/.terragrunt-cache/**,**/terraform.tfstate*,**/*tfplan*,**/terragrunt.hcl.lock*,**/*.lock.hcl,pipeline/**
        condition: succeeded()

      - script: |
          response=$(echo $SONARQUBE_SCANNER_PARAMS | sed -E 's#"sonar\.branch\.name":"[^"]+",##g')
          json=$(echo "$response" | sed 's/"sonar.token":\*\*\*/"sonar.token":"***"/')
          echo "$json" | jq
          echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$response"
        displayName: "⚙️ Set Variable — SONARQUBE_SCANNER_PARAMS"
        condition: succeeded()

      - task: SonarQubeAnalyze@7
        displayName: "📡 Run Sonar Analysis"
        condition: succeeded()

      - task: SonarQubePublish@7
        displayName: "📤 Publish Static Code Analysis Results"
        inputs:
          pollingTimeoutSec: 400
        condition: succeeded()

      - script: |
          echo "🔎 Validando Quality Gate..."
          PROJECT_KEY="$(Build.Repository.Name)"

          # Obtener estado del Quality Gate
          status=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$PROJECT_KEY")
          metrics_response=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/measures/component?component=$PROJECT_KEY&metricKeys=coverage,duplicated_lines_density")
          project_info=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/components/show?component=$PROJECT_KEY")

          coverage=$(echo "$metrics_response" | jq -r '.component.measures[] | select(.metric=="coverage") | .value')
          duplication=$(echo "$metrics_response" | jq -r '.component.measures[] | select(.metric=="duplicated_lines_density") | .value')
          status_code=$(echo "$status" | jq -r '.projectStatus.status')

          # Obtener Quality Gate Name y Quality Profile Name
          quality_gate=$(echo "$status" | jq -r '.projectStatus.qualityGate.name // "N/A"')
          quality_profile=$(echo "$project_info" | jq -r '.component.qualityProfile // "N/A"')
          language=$(echo "$project_info" | jq -r '.component.language // "N/A"')

          echo ""
          echo "🔹 Proyecto:        $PROJECT_KEY"
          echo "📊 Estado:          $status_code"
          echo ""

          if [[ "$status_code" == "ERROR" ]]; then
            echo -e "\n##vso[task.logissue type=error]⚠️ El proyecto no cumple con los Qualitys."
            exit 99
          else
            echo -e "\n✅ El proyecto cumple con los Qualitys."
          fi
        displayName: "🛡️ Quality Gate Check: $(Build.Repository.Name)"
        condition: succeeded()
        # continueOnError: true
        env:
          SONAR_TOKEN: $(SONAR_TOKEN)
          SONAR_HOST_URL: $(SONAR_HOST_URL)

  - job: "Checkov_infrastructure"
    displayName: "🛡️ Checkov - IaC scan"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-iac.yml

    steps:
      - task: Bash@3
        displayName: 'Checkov - IaC scan'
        inputs:
          targetType: 'inline'
          script: |
            docker run --rm \
              -v $(System.DefaultWorkingDirectory):/workdir \
              bridgecrew/checkov:latest \
              -d /workdir \
              --framework terraform \
              --hard-fail-on HIGH,CRITICAL \
              --skip-check CKV_AWS_59 \
              --skip-check CKV_AWS_120 \
              --skip-check CKV_AWS_310 \
              --skip-check CKV_AWS_86 \
              --skip-check CKV_AWS_68 \
              --skip-check CKV_AWS_374 \
              --skip-check CKV_AWS_108 \
              --skip-check CKV_AWS_287 \
              --skip-check CKV_AWS_355 \
              --skip-check CKV_AWS_290 \
              --skip-check CKV_AWS_8 \
              --skip-check CKV_AWS_126 \
              --skip-check CKV_AWS_79 \
              --skip-check CKV_AWS_65 \
              --skip-check CKV_AWS_336 \
              --skip-check CKV_AWS_158 \
              --skip-check CKV_AWS_31 \
              --skip-check CKV_AWS_191 \
              --skip-check CKV_AWS_61 \
              --skip-check CKV_AWS_273 \
              --skip-check CKV_AWS_43 \
              --skip-check CKV_AWS_185 \
              --skip-check CKV_AWS_91 \
              --skip-check CKV_AWS_324 \
              --quiet
