jobs:
  - job: changes_files_frontend
    displayName: "🔍 changes files"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - script: |
          apps='[
            "app-administration-vue2",
            "app-sellers-vue2",
            "users"
          ]'

          echo -e "\n📦 Apps originales:"
          echo "$apps" | jq

          # Ejemplo: quitar "app-sellers-vue2"
          apps=$(echo "$apps" | jq -c '[.[] | select(. != "app-sellers-vue2")]')

          echo -e "\n📦 Apps despues de filtrar:"
          echo "$apps"

          # Exportamos como variable de salida del job
          echo "##vso[task.setvariable variable=apps;isOutput=true]$apps"
        name: SetApps
        displayName: "🔧 Filtrar apps (Bash)"
