jobs:
  - job: "semantic_version_microservices"
    displayName: "🏷️ version microservices"
    pool:
      name: "Azure Pipelines"
      vmImage: ubuntu-latest

    variables:
      - template: ../variables/groups-transversal-variables.yml

    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - script: |
          set -e
          echo "⚙️ Listando servicios ECS en invictus..."
          export CLUSTER="invictus"

          SERVICE_NAMES=$(aws ecs list-services --cluster "$CLUSTER" --query "serviceArns[]" --output text | awk -F/ '{print $NF}')
          if [[ -z "$SERVICE_NAMES" ]]; then
            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontraron servicios en el cluster $CLUSTER"
            exit 99
          fi

          printf '%s' $SERVICE_NAMES > service_names.txt
          echo -e "📂 File: service_names.txt"
          cat service_names.txt
        displayName: "🔎 Listar servicios ECS"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)

      - script: |
          set -e
          echo "⚙️ Consultando versiones en ECR..."
          ECR_REGISTRY="861262569826.dkr.ecr.us-east-1.amazonaws.com"
          CURRENT_BRANCH="$(Build.SourceBranch)"

          case "$CURRENT_BRANCH" in
            refs/heads/develop)   ENVIRONMENT="develop"; ;;
            refs/heads/staging)   ENVIRONMENT="qa"; ;;
            refs/heads/master)    ENVIRONMENT="prd"; ;;
            *)
              echo -e "\n##vso[task.logissue type=error]⚠️ Error: ENVIRONMENT [$CURRENT_BRANCH] no reconocido."
              exit 99
              ;;
          esac

          if [[ ! -f service_names.txt ]]; then
            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró el archivo service_names.txt"
            exit 99
          fi

          declare -A SERVICES=()
          while IFS= read -r SERVICE_NAME; do
            SERVICE_REPO="microservice-${SERVICE_NAME}-${ENVIRONMENT}"
            SERVICES["$SERVICE_NAME"]="$SERVICE_REPO"
          done < service_names.txt

          for SERVICE in "${!SERVICES[@]}"; do
            SERVICE_REPO="${SERVICES[$SERVICE]}"
            echo -e "
            🔍 Consultando versión para $SERVICE..."

            VERSION=$(aws ecr describe-images --repository-name "$SERVICE_REPO" --region "$AWS_DEFAULT_REGION" --query "reverse(sort_by(imageDetails, &imagePushedAt))[0]" --output json | jq -r '.imageTags // [] | map(select(. != "latest")) | .[0]')
            if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
              echo -e "\n##vso[task.logissue type=error]⚠️ No se encontró versión para -> $SERVICE_REPO"
              exit 99
            fi

            FULL_IMAGE="$ECR_REGISTRY/$SERVICE_REPO:$VERSION"
            SERVICES[$SERVICE]="$FULL_IMAGE"

            echo "Repo: $SERVICE_REPO → $VERSION"
            echo "Imagen: $FULL_IMAGE"
            echo "------------------------------------------------------------"
          done

          SERVICES_JSON=$(jq -n '{'
            "$(for k in "${!SERVICES[@]}"; do
                  echo ""$k": "${SERVICES[$k]}"," 
                done | sed '$s/,$//')"'
          }')
          echo "$SERVICES_JSON" > services.json

          mkdir -p $(Build.ArtifactStagingDirectory)/microservices
          cp services.json $(Build.ArtifactStagingDirectory)/microservices/version.json

          echo -e "📂 File: services.json"
          jq . "services.json"
        displayName: "🔎 Consultar versiones ECR"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "versions"
          publishLocation: "Container"
        displayName: "📥 Publish artifact version"
        condition: succeeded()
