jobs:
  - job: "semantic_version_microservices"
    displayName: "🏷️ version microservices"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - script: |
          echo "⚙️ Procesando microservices..."
          echo "Version: $(msVersion)"

          mkdir -p $(Build.ArtifactStagingDirectory)/$(msName)
          touch $(Build.ArtifactStagingDirectory)/$(msName)/version.json

          echo "{ \"ms\": \"$(msName)\", \"version\": \"$(msVersion)\" }" > $(Build.ArtifactStagingDirectory)/$(msName)/version.json
          echo -e "\n📂 File ./$(msName)/version.json"
          jq . "$(Build.ArtifactStagingDirectory)/$(msName)/version.json"
        displayName: "⚙️ Create version file for: $(msName)"
        condition: succeeded()
