jobs:
  - ${{ if eq(parameters.release, 'aws-s3') }}:
      - template: ./general/semantic-version-frontend.yml
        parameters:
          apps: ${{ parameters.apps }}

  #####################################################################

  - ${{ if eq(parameters.release, 'aws-s3-new') }}:
      - template: ./general/semantic-version-frontend-new.yml
        parameters:
          apps: ${{ parameters.apps }}

  #####################################################################

  - ${{ if eq(parameters.release, 'electron-new') }}:
      - template: ./general/semantic-version-electron-new.yml

  #####################################################################

  - ${{ if eq(parameters.release, 'exe') }}:
      - template: ./general/semantic-version-electron.yml

  #####################################################################

  - ${{ if eq(parameters.release, 'rpc') }}:
      - template: ./general/semantic-version-repository-configuration.yml
