jobs:
  - job: "create_tag_version_flutter"
    displayName: "🏷️ create tag version"
    pool:
      name: "Azure Pipelines"
      vmImage: ubuntu-latest

    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: "versions"
          downloadPath: "$(Pipeline.Workspace)/version-downloaded"
        displayName: "📥 Download Version"
        condition: succeeded()

      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            set -e
            git config user.name "pipeline"
            git config user.email "pipelineUX@ux.technology"
            git fetch --tags

            file_version="$(Pipeline.Workspace)/version-downloaded/versions/flutter/version.json"
            file_pubspec="$(Pipeline.Workspace)/version-downloaded/versions/pubspec/version.json"
            VERSION=$(jq -r .version "$file_version")
            PUBSPEC=$(jq -r .version "$file_pubspec")
            TAG="v${VERSION}+${PUBSPEC}"
            echo "🏷️ Tag a crear: ${TAG}"

            git fetch --tags
            if git rev-parse "${TAG}" >/dev/null 2>&1; then
              echo -e "\n##vso[task.logissue type=warning]⚠️ El tag ${TAG} ya existe"
            else
              git tag -a "${TAG}" -m "Release ${TAG}"
              git push origin "${TAG}"
              echo "✅ Tag publicado: ${TAG}"
            fi
        displayName: "🏷️ Create Tag Version"
        condition: succeeded()
