jobs:
  - job: apply_infrastructure_${{ parameters.region }}
    displayName: "🚀 terragrunt apply"
    timeoutInMinutes: 120
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-iac.yml
        parameters:
          region: ${{ parameters.region }}

    steps:
      - script: |
          echo -e "\n📋 Variables disponibles:"
          printenv | sort | grep -i "aws_" || true

          echo -e "\n📋 Parametros disponibles:"
          printenv | sort | grep -i "parameter_" || true
        displayName: "📋 Environment variables"
        condition: succeeded()

      - script: |
          echo "📥 Descargando Terragrunt $(terragruntVersion)..."
          aws s3 cp "s3://infrastructure-as-code-invictus/terragrunt/terragrunt-$(terragruntVersion)" "terragrunt"

          if [ ! -s terragrunt ]; then
            echo "##vso[task.logissue type=error]⚠️ Error: No se pudo descargar terragrunt $(terragruntVersion)"
            exit 99
          fi

          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

          echo -e "\n🚀 Terragrunt instalado correctamente:"
          terragrunt --version
        displayName: "🛠️ Instalando Terragrunt $(terragruntVersion)"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - script: |
          echo "📥 Descargando Terraform..."
          aws s3 cp "s3://infrastructure-as-code-invictus/terraform/terraform-$(terraformVersion)" "terraform"

          if [ ! -s terraform ]; then
            echo "##vso[task.logissue type=error]⚠️ Error: No se pudo descargar terraform $(terraformVersion)"
            exit 99
          fi

          chmod +x terraform
          sudo mv terraform /usr/local/bin/terraform

          echo -e "\n🚀 Terraform instalado correctamente:"
          terraform --version
        displayName: "🛠️ Instalando Terraform $(terraformVersion)"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - task: replacetokens@5
        inputs:
          targetFiles: |
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/**/terragrunt.hcl
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/root.hcl
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/backend.tf
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/provider.tf
          encoding: "auto"
          writeBOM: true
          actionOnMissing: "warn" # 'fail', 'warn' o 'ignore'
          keepToken: false
          tokenPrefix: "#{"
          tokenSuffix: "}#"
        displayName: "⚙️ Replace Tokens"
        condition: succeeded()

      - script: |
          set -e


          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/astro/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +
          
          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/awards/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/bff-administration/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/bff-integration/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/bff-sellers/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color


          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/biometrics/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/collected/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/conciliation/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/dynamic-storage/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/external-wager/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/generic-services/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/hierarchies/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/lotteries/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/lotteries-games/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/metabase/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/millonario/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/money-control/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/notifications/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/online-games/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/papelery/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/payment-voucher/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/payments/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/products/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/promotional/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/raffles/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/recharges/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/remittances/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/scheduler/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/security/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/sellers/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/shopping-cart/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/siga/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/transaction/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/transaction-astro/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/transaction-lotteries-games/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/transaction-notifier/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/transaction-recharges/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/wiretransfer/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/reports/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/notifier/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/legacy/aws-service-ecs
          terragrunt plan --all --non-interactive -no-color
          terragrunt apply --all --non-interactive -no-color

          cd $(Build.SourcesDirectory)
          find . -type d -name ".terragrunt-cache" -exec rm -rf {} +


          # cd $(Build.SourcesDirectory)
          # find . -type d -name ".terragrunt-cache" -exec rm -rf {} +
        displayName: "🚀 Apply Infrastructure"
        timeoutInMinutes: 120
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
