jobs:
  - job: apply_infrastructure_${{ parameters.region }}
    displayName: "🚀 terragrunt apply"
    timeoutInMinutes: 120
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-iac.yml
        parameters:
          region: ${{ parameters.region }}

    steps:
      - script: |
          echo -e "\n📋 Variables disponibles:"
          printenv | sort | grep -i "aws_" || true

          echo -e "\n📋 Parametros disponibles:"
          printenv | sort | grep -i "parameter_" || true
        displayName: "📋 Environment variables"
        condition: succeeded()

      - script: |
          echo "📥 Descargando Terragrunt 0.84.1..."
          curl -L "https://github.com/gruntwork-io/terragrunt/releases/download/v0.84.1/terragrunt_linux_amd64" -o terragrunt

          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

          echo "🚀 Terragrunt instalado:"
          terragrunt --version
        displayName: "🛠️ Instalando Terragrunt 0.84.1"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - script: |
          echo "📥 Descargando Terraform 1.12.0..."
          curl -L "https://releases.hashicorp.com/terraform/1.12.0/terraform_1.12.0_linux_amd64.zip" -o terraform.zip

          unzip terraform.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin/terraform

          echo "🚀 Terraform instalado:"
          terraform --version
        displayName: "🛠️ Instalando Terraform 1.12.0"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - task: replacetokens@5
        inputs:
          targetFiles: |
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/**/terragrunt.hcl
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/root.hcl
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/backend.tf
            $(Build.SourcesDirectory)/iac-terragrunt/invictus/provider.tf
          encoding: "auto"
          writeBOM: true
          actionOnMissing: "warn" # 'fail', 'warn' o 'ignore'
          keepToken: false
          tokenPrefix: "#{"
          tokenSuffix: "}#"
        displayName: "⚙️ Replace Tokens"
        condition: succeeded()

      - script: |
          set -e


          cd $(Build.SourcesDirectory)/iac-terragrunt/invictus/scheduler
          terragrunt plan --all --non-interactive -no-color
          terragrunt destroy --all --non-interactive -no-color


          # cd $(Build.SourcesDirectory)
          # find . -type d -name ".terragrunt-cache" -exec rm -rf {} +
        displayName: "🚀 Apply Infrastructure"
        timeoutInMinutes: 120
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
