jobs:
  - job: deploy_artifact
    displayName: "🚀 deploy artifact"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-backend.yml

    steps:
      - download: current
        artifact: npm-package
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))

      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "18.x"

      - script: |
          cat <<EOF > $(Pipeline.Workspace)/npm-package/.npmrc
          registry=https://pkgs.dev.azure.com/ux-technology/Invictus/_packaging/shared-npm-libraries/npm/registry/
          always-auth=true
          EOF

          cat $(Pipeline.Workspace)/npm-package/.npmrc
        displayName: "🔐 Configure npm registry"
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))

      - task: npmAuthenticate@0
        inputs:
          workingFile: $(Pipeline.Workspace)/npm-package/.npmrc
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))

      - script: |
          cd $(Pipeline.Workspace)/npm-package
          npm publish *.tgz --registry https://pkgs.dev.azure.com/ux-technology/Invictus/_packaging/shared-npm-libraries/npm/registry/
        displayName: "Publish to Azure Artifacts"
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))

      - script: |
          FEED_ID=$(curl -s -u :$AZURE_DEVOPS_CLI_PAT \
          "https://feeds.dev.azure.com/ux-technology/Invictus/_apis/packaging/feeds?api-version=7.1-preview.1" \
          | jq -r '.value[] | select(.name=="$(FEED_INTER_LIBRARIES)") | .id')

          echo "##vso[task.setvariable variable=FEED_ID]$FEED_ID"

          echo "Feed ID: $FEED_ID"
        displayName: "feed ID"
        env:
          AZURE_DEVOPS_CLI_PAT: $(PAT-AZ)

      - script: |
          PACKAGE=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")

          ENCODED_PACKAGE=$(printf '%s' "$PACKAGE" | jq -sRr @uri)

          CURRENT_BRANCH="$BUILD_SOURCEBRANCH"
          BRANCH="${CURRENT_BRANCH#refs/heads/}"

          case "$BRANCH" in
            staging)
              VIEW="Prerelease"
              ;;
            master)
              VIEW="Release"
              ;;
          esac

          echo "Package: $PACKAGE"
          echo "Encoded package: $ENCODED_PACKAGE"
          echo "Version: $VERSION"
          echo "View: $VIEW"

          # echo "Promoting package..."

          # ENCODED_PAT=$(echo -n ":$AZURE_DEVOPS_CLI_PAT" | base64 | tr -d '\n')

          # RESPONSE=$(curl -v -X PATCH "https://pkgs.dev.azure.com/ux-technology/Invictus/_apis/packaging/feeds/$(FEED_ID)/npm/$ENCODED_PACKAGE/versions/$VERSION?api-version=7.2-preview.1" \
          # -H "Content-Type: application/json" \
          # -H "Authorization: Basic $ENCODED_PAT" \
          # -d "{
          #     \"views\": {
          #       \"path\": \"/views/-\",
          #       \"op\": \"add\",
          #       \"value\": \"$VIEW\"
          #     }
          #   }")
          
          # echo "Respuesta de la API:"
          # echo "$RESPONSE"

        displayName: "Promote npm package"
        condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'develop'))
        env:
          AZURE_DEVOPS_CLI_PAT: $(PAT-AZ)