jobs:
  - job: deploy_transactions
    displayName: "🚀 deploy "
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables.yml
        parameters:
          red: ${{ parameters.red }}

    strategy:
      matrix:
        ${{ each pair in parameters.apps }}:
          ${{ pair.Key }}:
            msName: ${{ pair.Key }}
            msVersion: ${{ pair.Value }}

    steps:
      - script: |
          msCluster="$(msName)-ms-cluster"
          msService="$(msName)-ms-fg-service"
          filePath="$(System.DefaultWorkingDirectory)/taskdef-$msService.json"
          tmpFilePath="$(System.DefaultWorkingDirectory)/tmp-taskdef-$msService.json"


          echo "📣 Microservice:"
          echo "Name: $(msName)"
          echo "Cluster: $msCluster"
          echo "Service: $msService"
          echo "File Path: $filePath"
          echo "Tmp File Path: $tmpFilePath"

          echo "##vso[task.setvariable variable=msCluster]$msCluster"
          echo "##vso[task.setvariable variable=msService]$msService"
          echo "##vso[task.setvariable variable=filePath]$filePath"
          echo "##vso[task.setvariable variable=tmpFilePath]$tmpFilePath"
        displayName: "⚙️ Prepare deploy $(msName)"
        condition: succeeded()

      - script: |
          echo -e "\n🚀 Versión detectada para $(msName)..." 
          echo "Version: $(msVersion)"
        displayName: "🔍 Read Microservice Versions"
        condition: succeeded()

      - script: |
          echo "🔐 Iniciando login a AWS ECR..."
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
          docker login --username AWS --password-stdin $ACCOUNT_ID_DEPLOY.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        displayName: "🔐 Login to AWS ECR"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            CURRENT_BRANCH=$(echo $(Build.SourceBranch))
            REPO_NAME="microservice-transaction-prd"
            IMAGE_TAG="$(msVersion)"

            echo "🔍 Verificando si la imagen '$IMAGE_TAG' existe en '$REPO_NAME'..."

            if aws ecr describe-images \
                --repository-name "$REPO_NAME" \
                --image-ids imageTag=$IMAGE_TAG \
                --region "$AWS_DEFAULT_REGION" > /dev/null 2>&1; then
              echo "✅ Imagen encontrada en ECR."
            else
              echo "❌ Imagen no encontrada: $REPO_NAME:$IMAGE_TAG"
              exit 99
            fi
        displayName: "🔍 Verify image in ECR"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - script: |
          echo "🔍 Obteniendo task definition..."

          TASK_ARN=$(aws ecs describe-services \
            --cluster "$(msCluster)" \
            --services "$(msService)" \
            --query "services[0].taskDefinition" \
            --output text)

          echo "🆔 Task Definition actual: $TASK_ARN"
          echo "##vso[task.setvariable variable=taskDefinitionArn]$TASK_ARN"
        displayName: "🔍 Get Task Definition ARN"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)

      - script: |
          echo "📤 Exportando Task Definition..."

          aws ecs describe-task-definition \
            --task-definition "$(taskDefinitionArn)" \
            --query "taskDefinition" \
            --output json > "$(filePath)"

          echo -e "\n📁 File: $(filePath)"
          jq . "$(filePath)"
        displayName: "📤 Export Current Task Definition"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)

      - script: |
          NEW_IMAGE="861262569826.dkr.ecr.us-east-1.amazonaws.com/microservice-transaction-prd:$(msVersion)"

          echo "🔄 Actualizando imagen: $NEW_IMAGE"
          jq --arg IMG "$NEW_IMAGE" '
          del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )
          | .containerDefinitions[0].image = $IMG
          ' "$(filePath)" > "$(tmpFilePath)"

          mv "$(tmpFilePath)" "$(filePath)"
          echo -e "\n📁 File: $(filePath)"
          jq . "$(filePath)"
        displayName: "📝 Update Image in Task Definition"
        condition: succeeded()

      - script: |
          echo "📝 Registrando la nueva Task Definition en ECS..."
          NEW_TASK_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://"$(filePath)" \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo -e "\n🚀 Nueva Task registrada"
          echo "➡️ ARN: $NEW_TASK_ARN"

          echo "##vso[task.setvariable variable=taskDefinitionArnNew]$NEW_TASK_ARN"
        displayName: "📄 Register New Task Definition"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)

      - script: |
          echo "📣 Microservice:"
          echo "Name: $(msName)"
          echo "Cluster: $(msCluster)"
          echo "Service: $(msService)"
          echo "ARN: $(taskDefinitionArnNew)"

          echo -e "\n🔄 Actualizando el servicio con la nueva Task Definition..."
          # aws ecs update-service \
          #   --cluster "$(msCluster)" \
          #   --service "$(msService)" \
          #   --task-definition "$(taskDefinitionArnNew)" \
          #   --force-new-deployment > /dev/null

          echo -e "\n✅ Servicio actualizado correctamente"
        displayName: "🔄 Update Service with New Task Definition"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
