jobs:
  - job: deploy_repository_configuration
    displayName: "🚀 deploy repository configuration"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-rpc.yml
        parameters:
          region: ${{ parameters.region }}
          environments: ${{ parameters.environments }}

    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - script: |
          set -e
          echo -e "\n📦 Cargando al Bucket S3..."
          ls -l

          aws s3 cp . s3://configuration-$(ACCOUNT_ID_INVICTUS) --recursive --exclude "pipeline/*"
        displayName: "📤 Upload Configuration to S3"
        condition: and(succeeded(),
          not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')),
          not(startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')))
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)

      - script: |
          set -e
          echo "🔎 Verificando cambios en carpeta reports/..."
          if git diff --name-only HEAD~1 HEAD | grep -q "^reports/"; then 
            echo "✅ Se detectaron cambios en reports/ y no es develop, enviando mensaje a SQS"; 
            json_complete='{"event":"migration","streamNotifier":"Notifier","model":{"method":"insert","reports":[{"name":"modelos_invictus","type_card":"model"},{"name":"reportes_invictus","type_card":"question"},{"name":"archivos_cem","type_card":"question"}]}}'; 
            aws sqs send-message \
              --queue-url https://sqs.us-east-1.amazonaws.com/$(ACCOUNT_ID_INVICTUS)/Sellers \
              --message-body "$json_complete" \
              --delay-seconds 0
          else 
            echo "ℹ️ No se enviará mensaje a SQS: no hubo cambios en reports/"
          fi
        displayName: "🔍 Verify Changes in reports/"
        condition: and(succeeded(),
          not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')),
          not(startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')),
          ne(variables['Build.SourceBranch'], 'refs/heads/develop'))
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)

      - script: |
            DEPLOY_TIME=$(date -d "$BUILD_FINISHTIME -5 hours" "+%Y-%m-%d %H:%M UTC")
            BRANCH_NAME_MULTI=$environments
            BRANCH_NAME="$BUILD_SOURCEBRANCHNAME"

            if [[ "$BRANCH_NAME" == "master" ]]; then
              BRANCH_DEPLOY="${red:-red}"

            elif [[ "$BRANCH_NAME" == "develop" && "$BRANCH_NAME_MULTI" == "develop" ]]; then
              BRANCH_DEPLOY="develop"

            elif [[ "$BRANCH_NAME" == "staging" && "$BRANCH_NAME_MULTI" == "staging" ]]; then
              BRANCH_DEPLOY="staging"

            else
              BRANCH_DEPLOY="$BRANCH_NAME_MULTI"
            fi
            
            payload=$(cat <<EOF
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "summary": "Deployment successful",
              "themeColor": "00FF00",
              "title": "✅ Deployment exitoso $(Build.SourceBranchName)",
              "sections": [
                {
                  "facts": [
                    { "name": "Pipeline", "value": "$(Build.DefinitionName)" },
                    { "name": "Branch", "value": "$BRANCH_DEPLOY" },
                    { "name": "Build", "value": "$(Build.BuildNumber)" },
                    { "name": "Merged by", "value": "$(Build.RequestedFor)" },
                    { "name": "Deploy time", "value": "$DEPLOY_TIME" }
                  ],
                  "markdown": true
                }
              ]
            }
            EOF
            )

            curl -H "Content-Type: application/json" \
                 -d "$payload" \
                 $(URL_WEBHOOK_TEAMS)
        displayName: "📢 Post message to Teams"
        env:
          red: ${{ parameters.region }}
          environments: ${{ parameters.environments }}
