jobs:
  - job: deploy_micro_service
    displayName: "🚀 Deploy Microservice"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-backend.yml
        parameters:
          region: ${{ parameters.region }}

    steps:
      - script: |
          echo -e "\nℹ️ Original msName: $(Build.Repository.Name)"
          cleanName=$(echo "$(Build.Repository.Name)" | sed -E 's/^microservice-//; s/-invictus$//')

          echo -e "\nℹ️ Nombre limpio: $cleanName"
          echo "##vso[task.setvariable variable=cleanMsName]$cleanName"
        displayName: "🌐 Deploying $(Build.Repository.Name)"
        condition: succeeded()

      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: "versions"
          downloadPath: "$(Pipeline.Workspace)/version-downloaded"
        displayName: "📥 Download Version"
        condition: succeeded()

      - script: |
          VERSION_FILE="$(Pipeline.Workspace)/version-downloaded/versions/microservice/version.json"

          echo -e "\n📁 Archivo version.json:"
          ls -la "$VERSION_FILE"
          cat "$VERSION_FILE"

          if [[ -f "$VERSION_FILE" ]]; then
            VERSION=$(jq -r '.version' $VERSION_FILE)
            echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
            echo "##vso[task.setvariable variable=version]$VERSION"
          else
            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
            exit 99
          fi
        displayName: "📚 Read Version"
        condition: succeeded()

      - script: |
          set -e
          echo -e "\n🔐 Logging in to ECR..."
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
          docker login --username AWS --password-stdin $ACCOUNT_ID_DEPLOY.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        displayName: "🔐 Login to AWS ECR"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - script: |
          REPO_NAME="$(Build.Repository.Name)"
          echo -e "\nℹ️ Repositorio: $REPO_NAME"

          if [[ "$REPO_NAME" == "microservice-notifier-invictus" ]]; then
              CLEAN_NAME="notifier"
          else
              CLEAN_NAME="${REPO_NAME%-invictus}"         # quita solo el sufijo -invictus
          fi

          echo -e "\nℹ️ Clean Repositorio: $CLEAN_NAME"
          echo "##vso[task.setvariable variable=clean_name_ecr]$CLEAN_NAME"
        displayName: "📛 Set ECR Repository Name"
        condition: succeeded()

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            CURRENT_BRANCH=$(echo $(Build.SourceBranch))

            if [[ "$CURRENT_BRANCH" == refs/heads/develop ]]; then
              raw_branch=$(Build.SourceBranch)
              clean_branch=$(echo "$raw_branch" | sed 's#refs/heads/##')
            fi

            if [[ "$CURRENT_BRANCH" == refs/heads/staging ]]; then
              clean_branch=qa
            fi

            if [[ "$CURRENT_BRANCH" == refs/heads/master ]]; then
              clean_branch=prd
            fi

            REPO_NAME="pruebas-$(clean_name_ecr)-$clean_branch"
            IMAGE_TAG="$(version)"

            echo "🔍 Verificando si la imagen '$IMAGE_TAG' existe en '$REPO_NAME'..."

            if aws ecr describe-images \
                --repository-name "$REPO_NAME" \
                --image-ids imageTag=$IMAGE_TAG \
                --region "$AWS_DEFAULT_REGION" > /dev/null 2>&1; then
              echo "✅ Imagen encontrada en ECR."
            else
              echo -e "\n##vso[task.logissue type=error]⚠️ Imagen no encontrada: $REPO_NAME:$IMAGE_TAG"
              exit 99
            fi
        displayName: "🔍 Verify if Image Exists in ECR"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - script: |
          export AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY
          export AWS_REGION

          BRANCH_NAME="$BUILD_SOURCEBRANCHNAME"
          REPO_NAME="$BUILD_REPOSITORY_NAME"
          RED="${red:-}"

          echo "🏠 Red: $RED"
          echo "📦 Repo: $REPO_NAME"
          echo "🌿 Branch: $BRANCH_NAME"

          # 🧹 Limpieza base del nombre (para BFFs)
          if [[ "$REPO_NAME" == bff-*-invictus ]]; then
              CLEAN_NAME="${REPO_NAME#bff-}"
              CLEAN_NAME="${CLEAN_NAME%-invictus}"
              name_bff="bff-${CLEAN_NAME}-invictus"
          else
              CLEAN_NAME="${REPO_NAME%-invictus}"
          fi

          echo "🧩 Clean Name: $CLEAN_NAME"

          CLUSTER="${CLUSTER:-$cluster_name}"       # cluster heredado de variable YAML si existe
          SERVICES="${SERVICES:-$service_name}"     # service heredado

          # ⚙️ Función auxiliar para asignar si aplica
          set_cluster_service() {
            local new_cluster="$1"
            local new_service="$2"
            CLUSTER="$new_cluster"
            SERVICES="$new_service"
          }

          case "$(cleanMsName)" in
            notifier)
              if [[ "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == "staging" || "$RED" == "cap" || "$RED" == "antioquia" ]]; then
                set_cluster_service "msnotifier-cluster" "msnotifier-fg-service"
              fi
              ;;
            raffle)
              if [[ "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == "staging" || "$RED" == "cap" || "$RED" == "antioquia" ]]; then
                set_cluster_service "raffles-ms-cluster" "raffles-ms-fg-service"
              elif [[ "$RED" != "cap" && "$RED" != "antioquia" && "$BRANCH_NAME" != "develop" && "$BRANCH_NAME" != "staging" ]]; then
                SERVICES="raffles"
              fi
              ;;
          esac

          # ⚙️ Casos específicos para BFFs
          if [[ "$REPO_NAME" == "$name_bff" ]]; then
              if [[ "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == "staging" || "$RED" == "cap" || "$RED" == "antioquia" ]]; then
                  set_cluster_service "bff-${CLEAN_NAME}-cluster" "bff-${CLEAN_NAME}-fg-service"
              fi
          fi

          echo "🛡️ Cluster: $CLUSTER"
          echo "📦 Services: $SERVICES"

          echo -e "\nℹ️ Obteniendo task definition..."
          arn=$(aws ecs describe-services \
            --cluster $CLUSTER \
            --services $SERVICES \
            --query 'services[0].taskDefinition' \
            --output text \
            --region $(AWS_DEFAULT_REGION))
            
          if [[ -z "$arn" || "$arn" == "None" ]]; then
            echo -e "\n##vso[task.logissue type=error]❌ Error: No se encontró task definition para el servicio $SERVICES en el cluster $CLUSTER"
            exit 99
          else
             echo -e "\n✅ Task Definition ARN: $arn"
          fi
          echo "##vso[task.setvariable variable=taskDefinitionArn]$arn"
          echo "##vso[task.setvariable variable=cluster_name]$CLUSTER"
          echo "##vso[task.setvariable variable=service_name]$SERVICES"
        displayName: "🔗 Get Task Definition ARN"
        condition: and(succeeded(),
          ne(variables['cleanMsName'], 'transaction'))
        env:
          red: ${{ parameters.region }}
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)

      - script: |
          export AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY
          export AWS_REGION

          BRANCH_NAME="$BUILD_SOURCEBRANCHNAME"
          REPO_NAME="$BUILD_REPOSITORY_NAME"
          RED="${red:-}"

          echo "🏠 Red: $RED"
          echo "📦 Repo: $REPO_NAME"
          echo "🌿 Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == "staging" || "$RED" == "cap" || "$RED" == "antioquia" ]]; then
            # ⚡ FGs
            clusters=("transaction-ms-cluster" "transaction-astro-ms-cluster" "transaction-lg-ms-cluster" "transaction-recharges-ms-cluster")
            services=("transaction-ms-fg-service" "transaction-astro-ms-fg-service" "transaction-lg-ms-fg-service" "transaction-recharges-ms-fg-service")
          else
              # 🌐 Producción normal
              clusters=("invictus" "invictus" "invictus" "invictus")
              services=("transaction" "transaction-astro" "transaction-lotteries-games" "transaction-recharges")
          fi

          index=1
          for i in 0 1 2 3; do
              C="${clusters[$i]}"
              S="${services[$i]}"

              echo "-------------------------"
              echo "🛡️ Cluster: $C"
              echo "📦 Services: $S"
              echo "Obteniendo task definition..."

              arn=$(aws ecs describe-services \
                --cluster "$C" \
                --services "$S" \
                --query 'services[0].taskDefinition' \
                --output text \
                --region "$AWS_DEFAULT_REGION")

              if [[ -z "$arn" || "$arn" == "None" ]]; then
                echo "❌ Error: No se encontró taskDefinition para $S en $C"
                exit 99
              fi

              echo "✅ TaskDef ARN: $arn"

              # Set variables por cada uno
              echo "##vso[task.setvariable variable=cluster_name_${index}]$C"
              echo "##vso[task.setvariable variable=service_name_${index}]$S"
              echo "##vso[task.setvariable variable=taskDefinitionArn_${index}]$arn"

              ((index++))
          done
        displayName: "🔗 Get Task Definition ARN"
        condition: and(succeeded(),
          eq(variables['cleanMsName'], 'transaction'))
        env:
          red: ${{ parameters.region }}
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)

      - script: |
          echo -e "\nℹ️ Obteniendo family de task definition..."
          ARN='$(taskDefinitionArn)'
          echo $ARN
          FAMILY=$(echo $ARN | cut -d'/' -f2 | cut -d':' -f1)
          echo "##vso[task.setvariable variable=taskFamily]$FAMILY"
        displayName: "📌 Extract Family from ARN"
        condition: and(succeeded(),
          ne(variables['cleanMsName'], 'transaction'))
      
      - script: |
          echo -e "\nℹ️ Extrayendo FAMILY para todos los taskDefinitionArn_X..."

          echo $(taskDefinitionArn_1)
          for i in 0 1 2 3; do
            ARN_VAR="taskDefinitionArn_${i}"
            ARN_VALUE="${!ARN_VAR}"

            echo -e "\n📌 Procesando índice $i"
            echo "ARN recibido: $ARN_VALUE"

            if [[ -z "$ARN_VALUE" ]]; then
              echo "❌ Error: ARN vacío para índice $i"
              exit 98
            fi

            FAMILY=$(echo "$ARN_VALUE" | cut -d'/' -f2 | cut -d':' -f1)
            echo "FAMILY: $FAMILY"

            echo "##vso[task.setvariable variable=taskFamily_${i}]$FAMILY"
          done
        displayName: "📌 Extract Family from ARN"
        condition: and(succeeded(),
          eq(variables['cleanMsName'], 'transaction'))

      - script: |
          export AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY
          export AWS_REGION

          echo -e "\nℹ️ Obteniendo definición actual..."
          aws ecs describe-task-definition \
            --task-definition $(taskDefinitionArn) \
            --query 'taskDefinition' \
            > taskdef.json
          cat taskdef.json
        displayName: "📑 Get Current Task Definition"
        condition: and(succeeded(),
          ne(variables['cleanMsName'], 'transaction'))
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
      
      - script: |
          export AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY
          export AWS_REGION

          echo -e "\nℹ️ Obteniendo CURRENT TASK DEFINITIONS (4 servicios transaction)..."

          for i in 0 1 2 3; do
            ARN_VAR="taskDefinitionArn_${i}"
            ARN_VALUE='$(taskDefinitionArn_${i})'

            if [[ -z "$ARN_VALUE" ]]; then
              echo "❌ ARN vacío para índice $i"
              exit 97
            fi

            echo -e "\n----------------------------"
            echo "📌 Índice: $i"
            echo "📝 ARN: $ARN_VALUE"
            echo "📑 Descargando task definition…"

            aws ecs describe-task-definition \
              --task-definition "$ARN_VALUE" \
              --query 'taskDefinition' \
              > "taskdef_${i}.json"

            echo "✅ Archivo generado: taskdef_${i}.json"
          done
        displayName: "📑 Get Current Task Definition"
        condition: and(succeeded(),
          eq(variables['cleanMsName'], 'transaction'))
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)

      # - script: |
      #     newTag="$(version)"

      #     jq --arg newTag "$newTag" '
      #       .containerDefinitions |= map(
      #         .image |= (split(":")[0] + ":" + $newTag)
      #       )
      #     ' taskdef.json > new-taskdef-$(cleanMsName).json

      #     echo -e "\nℹ️ Imagen actualizada con nuevo tag: $newTag"
      #     cat new-taskdef-$(cleanMsName).json
      #   displayName: "📝 Update image tag in task definition"
      #   condition: succeeded()

      # - script: |
      #     jq '{
      #       family,
      #       taskRoleArn,
      #       executionRoleArn,
      #       networkMode,
      #       containerDefinitions,
      #       volumes,
      #       placementConstraints,
      #       requiresCompatibilities,
      #       cpu,
      #       memory,
      #       tags,
      #       pidMode,
      #       ipcMode,
      #       proxyConfiguration,
      #       inferenceAccelerators,
      #       ephemeralStorage,
      #       runtimePlatform
      #     } | with_entries(select(.value != null))' new-taskdef-$(cleanMsName).json > new-taskdef-$(cleanMsName)-ecs.json

      #     cat new-taskdef-$(cleanMsName)-ecs.json
      #   displayName: "🧹 Clean up attributes"
      #   condition: succeeded()

      # - script: |
      #     export AWS_REGION
      #     export AWS_ACCESS_KEY_ID
      #     export AWS_SECRET_ACCESS_KEY

      #     output=$(aws ecs register-task-definition \
      #     --cli-input-json file://new-taskdef-$(cleanMsName)-ecs.json \
      #     --region $AWS_DEFAULT_REGION)

      #     arn=$(echo $output | jq -r '.taskDefinition.taskDefinitionArn')

      #     echo -e "\nℹ️ Nueva Task Definition ARN: $arn"
      #     echo "##vso[task.setvariable variable=taskDefinitionArnNew]$arn"
      #   displayName: "🆕 Register New Task Definition"
      #   condition: succeeded()
      #   env:
      #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
      #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
      #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)

      # - script: |
      #     export AWS_ACCESS_KEY_ID
      #     export AWS_SECRET_ACCESS_KEY
      #     export AWS_REGION

      #     echo "🔹 Task Definition ARN : $(taskDefinitionArnNew)"
      #     echo "🔹 Cluster             : $(cluster_name)"
      #     echo "🔹 Service             : $(service_name)"

      #     aws ecs update-service \
      #       --cluster $(cluster_name) \
      #       --service $(service_name) \
      #       --task-definition $(taskDefinitionArnNew) \
      #       --region $AWS_DEFAULT_REGION
      #   displayName: "⚡ Deploy New Task Definition to Service"
      #   condition: succeeded()
      #   env:
      #     AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
      #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
      #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
