jobs:
  - job: deploy_micro_frontend
    displayName: "🚀 deploy microfrontend"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-frontend.yml
        parameters:
          region: ${{ parameters.region }}

    strategy:
      matrix:
        ${{ each ms in parameters.apps }}:
          ${{ ms }}:
            msName: ${{ ms }}

    steps:
      - script: |
          VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/$(msName)/version.json"
          if [[ -f "$VERSION_FILE" ]]; then
            VERSION=$(jq -r '.version' $VERSION_FILE)
            echo -e "\n🚀 Versión detectada para $(msName): $VERSION"
            echo "##vso[task.setvariable variable=msVersion]$VERSION"
          else
            echo "##vso[task.logissue type=error]❌ No se encontró archivo de versión para: $(msName)"
            exit 99
          fi
        displayName: "📚 Read Version"
        condition: succeeded()

      - script: |
          if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
            fileselect=app-legacy
            echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
            echo "##vso[task.setvariable variable=file]$fileselect"
          else
            fileselect=apps
            echo -e "\nℹ️ Ruta de archivo del micro frontend: $fileselect"
            echo "##vso[task.setvariable variable=file]$fileselect"
          fi
        displayName: "📂 Select Directory"
        condition: succeeded()

      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: dists
          path: $(Pipeline.Workspace)/downloaded-dists
        displayName: "📥 Download Dists"
        condition: succeeded()

      - script: |
          set -e
          echo -e "\n📦 Cargando al Bucket S3..."

          BASE_PATH="$(Pipeline.Workspace)/downloaded-dists/dists/$(region)/$(msName)"
          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
          ls -l "$BASE_PATH"

          if [[ "$(msName)" == "app-administration-vue2" || "$(msName)" == "app-sellers-vue2" ]]; then
            msName=$(msName)
            msName=${msName%-vue2}
          else 
            msName=$(msName)
          fi

          aws s3 cp $BASE_PATH s3://mf-$msName-$(ACCOUNT_ID_INVIC)/$(msVersion)/ --recursive
        displayName: "📤 Upload Bucket S3"
        condition: succeeded()
        env:
          region: ${{ parameters.region }}




      - script: |
          set -e
          echo -e "\n📦 Cargando al Bucket S3..."

          BASE_PATH="$(Pipeline.Workspace)/downloaded-dists/dists//$(msName)"

          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
          ls -l "$BASE_PATH"

          aws s3 cp "$BASE_PATH" "s3://electron-app-$(ACCOUNT_ID_INVIC)/linux/" --recursive

          echo -e "\n✅ Archivos subidos exitosamente."
          echo "🔗 APP: InvictusUX-$(msVersion).AppImage"
          echo "🔗 URL: https://electron-app-$(ACCOUNT_ID_INVIC).s3.us-east-1.amazonaws.com/InvictusUX-$(msVersion).AppImage"

        displayName: "🐧 Upload Bucket S3 Linux"
        condition: succeeded()
        env:
          region: ${{ parameters.region }}

          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)

      - script: |
          set -e
          echo -e "\n📦 Cargando al Bucket S3..."

          BASE_PATH="$(Pipeline.Workspace)/electron-artifacts/electron/windows"
          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
          ls -l "$BASE_PATH"

          aws s3 cp "$BASE_PATH" "s3://electron-app-$(ACCOUNT_ID_INVIC)/windows/" --recursive

          echo -e "\n✅ Archivos subidos exitosamente."
          echo "🔗 APP: InvictusUX Setup $(msVersion).exe"
          echo "🔗 URL: https://electron-app-$(ACCOUNT_ID_INVIC).s3.us-east-1.amazonaws.com/InvictusUX+Setup+$(msVersion).exe"

        displayName: "🖥️ Upload Bucket S3 Windows"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVIC)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVIC)
