jobs:
  - job: deploy_artifact
    displayName: "🚀 deploy artifact"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    steps:
      - download: current
        artifact: npm-package

      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "18.x"

      - script: |
          cat <<EOF > $(Pipeline.Workspace)/npm-package/.npmrc
          registry=https://pkgs.dev.azure.com/ux-technology/Invictus/_packaging/shared-npm-libraries/npm/registry/
          always-auth=true
          EOF

          cat $(Pipeline.Workspace)/npm-package/.npmrc
        displayName: "🔐 Configure npm registry"

      # AUTENTICACIÓN AZURE ARTIFACTS
      - task: npmAuthenticate@0
        inputs:
          workingFile: $(Pipeline.Workspace)/npm-package/.npmrc

      - script: |
          cd $(Pipeline.Workspace)/npm-package
          npm publish *.tgz --registry https://pkgs.dev.azure.com/ux-technology/Invictus/_packaging/shared-npm-libraries/npm/registry/
        displayName: "Publish to Azure Artifacts"
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))

      - script: |
          PACKAGE=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")

          CURRENT_BRANCH="$BUILD_SOURCEBRANCH"
          BRANCH="${CURRENT_BRANCH#refs/heads/}"

          case "$BRANCH" in
            staging)
              VIEW="prerelease"
              ;;
            master)
              VIEW="release"
              ;;
          esac

          echo "Package: $PACKAGE"
          echo "Version: $VERSION"
          echo "View: $VIEW"

          curl -X PATCH \
            -H "Content-Type: application/json-patch+json" \
            -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
            -d "[
                  {
                    \"op\": \"add\",
                    \"path\": \"/views/-\",
                    \"value\": \"${VIEW}\"
                  }
                ]" \
            "https://pkgs.dev.azure.com/ux-technology/Invictus/_apis/packaging/feeds/shared-npm-libraries/npm/packages/${PACKAGE}/versions/${VERSION}?api-version=7.1-preview.1"

        displayName: "Promote npm package"
        condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'develop'))
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)