jobs:
  - job: deploy_electron
    displayName: "🚀 deploy electron"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-electron.yml
        parameters:
          region: ${{ parameters.region }}

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: "electron"
          downloadPath: "$(Pipeline.Workspace)/electron-artifacts"
        displayName: "📥 Download Electron Artifacts"
        condition: succeeded()

      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: "versions"
          downloadPath: "$(Pipeline.Workspace)/versions-downloaded"
        displayName: "📥 Download Version"
        condition: succeeded()

      - script: |
          VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/electron/version.json"
          if [[ -f "$VERSION_FILE" ]]; then
            VERSION=$(jq -r '.version' $VERSION_FILE)
            echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
            echo "##vso[task.setvariable variable=msVersion]$VERSION"
          else
            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
            exit 99
          fi
        displayName: "📚 Read Version"
        condition: succeeded()

      - script: |
          CURRENT_BRANCH="$(Build.SourceBranch)"
          environment="unknown"

          case "$CURRENT_BRANCH" in
            refs/heads/feature/*) environment="dev"; ;;
            refs/heads/develop)   environment="dev"; ;;
            refs/heads/staging)   environment="qa"; ;;
            refs/heads/master) 
              case "$region" in
                "antioquia") environment="matrixtech"; ;;
                "cap")       environment="cap"; ;;
                "tolima")    environment="seapto"; ;;
                "huila")     environment="suchance"; ;;
                "cauca")     environment="acertemos"; ;;
                "boyaca")    environment="jer"; ;;
                "santander") environment="laperla"; ;;
              esac ;;
          esac

          if [[ "$environment" = "unknown" ]]; then
            echo -e "\n##vso[task.logissue type=error]⚠️ Environment [$environment] no reconocido"
            exit 99
          fi

          echo "##vso[task.setvariable variable=environment]$environment"
          echo -e "\n✅ Environment asignado exitosamente:"
          echo "Environment: $environment"

        displayName: "⚙️ Generate .env"
        condition: succeeded()
        env:
          region: ${{ parameters.region }}

      - script: |
          set -e
          echo -e "\n📦 Cargando al Bucket S3..."

          BASE_PATH="$(Pipeline.Workspace)/electron-artifacts/electron/linux"
          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
          ls -l "$BASE_PATH"
          echo ""

          aws s3 cp "$BASE_PATH" "s3://e-remote/invictus-electron/linux/$(environment)" --recursive --acl public-read

          echo -e "\n✅ Archivos subidos exitosamente."
          echo "🔗 APP: InvictusUX-$(msVersion).AppImage"
          echo "🔗 URL: https://e-remote.s3.us-east-1.amazonaws.com/invictus-electron/linux/$(environment)/InvictusUX-$(msVersion).AppImage"

        displayName: "🐧 Upload Bucket S3 Linux"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)

      - script: |
          set -e
          echo -e "\n📦 Cargando al Bucket S3..."

          BASE_PATH="$(Pipeline.Workspace)/electron-artifacts/electron/windows"
          echo -e "\n📂 Archivos a cargar: $BASE_PATH"
          ls -l "$BASE_PATH"
          echo ""

          aws s3 cp "$BASE_PATH" "s3://e-remote/invictus-electron/windows/$($env:environment)" --recursive --acl public-read

          echo -e "\n✅ Archivos subidos exitosamente."
          echo "🔗 APP: InvictusUX Setup $(msVersion).exe"
          Write-Host "🔗 URL: https://e-remote.s3.us-east-1.amazonaws.com/invictus-electron/windows/$($env:environment)/InvictusUX+Setup+$($env:version).exe"

        displayName: "🖥️ Upload Bucket S3 Windows"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
