jobs:
  - job: deploy_flutter
    displayName: "🚀 deploy flutter"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables-flutter.yml
        parameters:
          region: ${{ parameters.region }}

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: "flutter"
          downloadPath: "$(Pipeline.Workspace)/flutter-artifacts"
        displayName: "📥 Download Flutter Artifacts"
        condition: succeeded()

      - script: |
          VERSION_FILE="$(Pipeline.Workspace)/versions-downloaded/versions/flutter/version.json"

          echo -e "\n📁 Archivo version.json:"
          ls -la "$VERSION_FILE"
          cat "$VERSION_FILE"

          if [[ -f "$VERSION_FILE" ]]; then
            VERSION=$(jq -r '.version' $VERSION_FILE)
            echo -e "\n🚀 Versión detectada para $(Build.Repository.Name): $VERSION"
            echo "##vso[task.setvariable variable=version]$VERSION"
          else
            echo -e "\n##vso[task.logissue type=error]⚠️ No se encontro archivo de versión para $(Build.Repository.Name)"
            exit 99
          fi
        displayName: "📚 Read Version"
        condition: succeeded()

      - script: |
          CURRENT_BRANCH="$(Build.SourceBranch)"
          environment="unknown"

          case "$CURRENT_BRANCH" in
            refs/heads/feature/*) environment="dev"; ;;
            refs/heads/develop) environment="dev"; ;;
            refs/heads/staging) environment="qa"; ;;
            refs/heads/master) 
              case "$region" in
                "antioquia") environment="prd-gana"; ;;
                "cap")       environment="prd-cap"; ;;
                "tolima")    environment="prd-seapto"; ;;
                "huila")     environment="prd-suchance"; ;;
                "cauca")     environment="prd-acertemos"; ;;
                "boyaca")    environment="prd-jer"; ;;
                "santander") environment="prd-laperla"; ;;
              esac ;;
          esac

          if [[ "$environment" = "unknown" ]]; then
            echo -e "\n##vso[task.logissue type=error]⚠️ Environment [$environment] no reconocido"
            exit 99
          fi

          echo "##vso[task.setvariable variable=environment]$environment"

          echo -e "\nℹ️ Varibles de entorno:"
          echo "Environment: $environment"
        displayName: "⚙️ Generate Environment"
        condition: succeeded()
        env:
          region: ${{ parameters.region }}

      - script: |
          echo -e "\n📦 Cargando al Bucket S3..."
          echo "APK: $(apk-name)"
          echo "Environment: $environment"

          mkdir -p build/app/outputs/flutter-apk/$(environment)
          cp build/app/outputs/flutter-apk/$(apk-name) build/app/outputs/flutter-apk/$(environment)

          echo -e "\n📁 Archivos a cargar:"
          ls -l build/app/outputs/flutter-apk/$(environment)
          
          
          #aws s3 cp build/app/outputs/flutter-apk/$(environment) s3://repository-native/app-seller/android/$(environment) --recursive --acl public-read
          aws s3 cp build/app/outputs/flutter-apk/$(environment) s3://repository-native/app-seller/android/dev-test --recursive --acl public-read

          echo -e "\n✅ Archivos subidos exitosamente."
          echo "🔗 APK: $(apk-name)"
          #echo "🔗 URL: https://repository-native.s3.us-east-1.amazonaws.com/app-seller/android/$(environment)/$(apk-name)"
          
          echo "🔗 URL: https://repository-native.s3.us-east-1.amazonaws.com/app-seller/android/dev-test/$(apk-name)"

        displayName: "📤 Upload Bucket S3"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_DEPLOY)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_DEPLOY)
