jobs:
  - job: reload_microservices
    displayName: "🚀 reload microservices"
    pool:
      name: "Azure Pipelines"
      VmImage: ubuntu-22.04

    variables:
      - template: ../../variables/groups-transversal-variables.yml
        parameters:
          release: ${{ parameters.release }}
          services: ${{ parameters.services }}

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: "versions"
          downloadPath: "$(Pipeline.Workspace)/versions-downloaded"
        displayName: "📥 Download Version"
        condition: succeeded()

      - script: |
          set -e
          cp $(Pipeline.Workspace)/versions-downloaded/versions/microservices/version.json $(System.DefaultWorkingDirectory)/services.json
          export CLUSTER="invictus"

          echo "✅ Servicios a reiniciar:"
          jq . services.json
          echo ""

          for SERVICE in $(jq -r '.[]' services.json); do
            echo "🔄 Reiniciando $SERVICE..."

            aws ecs update-service \
              --cluster "$CLUSTER" \
              --service "$SERVICE" \
              --force-new-deployment > /dev/null 2>&1

            echo "✅ $SERVICE reiniciado correctamente"
            echo -e "---------------------------------------------\n"
          done
        displayName: "🚀 Reiniciando Microservices"
        condition: succeeded()
        env:
          AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_INVICTUS)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_INVICTUS)
