jobs:
  - deployment: push_versions
    displayName: "🔐 serial git push (version/*)"
    dependsOn: "deploy_electron"
    condition: in(dependencies.deploy_electron.result, 'Succeeded', 'SucceededWithIssues')
    environment: git-version-lock
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              fetchDepth: 0
              persistCredentials: true
              fetchTags: false

            - download: current
              artifact: versions
              displayName: "📥 Download Versions"

            - task: Bash@3
              inputs:
                targetType: inline
                script: |
                  set -e
                  raw_branch=$(Build.SourceBranch)
                  clean_branch=$(echo "$raw_branch" | sed 's#refs/heads/##')

                  git config user.name "pipeline"
                  git config user.email "pipelineUX@ux.technology"

                  git fetch origin version/$clean_branch
                  git checkout -B version/$clean_branch origin/version/$clean_branch

                  file=$(Pipeline.Workspace)/versions/electron/version.json


                  cleanNEXT_VERSION=$(jq -r .version "$file")
                  jq --arg version "$cleanNEXT_VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json

                  echo "🔧 $(Build.Repository.Name) → $cleanNEXT_VERSION"

                  git add package.json
                  git commit -m "chore($(Build.Repository.Name)): bump version to $cleanNEXT_VERSION"
                  git push origin version/$clean_branch
                  echo "##vso[build.updatebuildnumber]$cleanNEXT_VERSION"
              displayName: "⚡ Commit Version & Push — $(Build.Repository.Name)"
              condition: succeeded()
