jobs:
  - deployment: push_versions
    displayName: "🔐 Serial Git Push (version/*)"
    condition: in(dependencies.deploy_micro_service.result, 'Succeeded', 'SucceededWithIssues')
    environment: git-version-lock
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            fetchDepth: 0
            persistCredentials: true

          - download: current
            artifact: versions
            displayName: "📥 Download Versions"

          - script: |
              raw_branch=$(Build.SourceBranch)
              clean_branch=$(echo "$raw_branch" | sed 's#refs/heads/##')

              git config user.name "pipeline"
              git config user.email "pipelineUX@ux.technology"

              git fetch origin version/$clean_branch
              git checkout -B version/$clean_branch origin/version/$clean_branch

              file=(Pipeline.Workspace)/versions/microservice/version.json

              version=$(jq -r .version "$file")
              jq --arg version "$version" \
                '.version = $version' \
                "package.json" > tmp.json && mv tmp.json "$package.json"

              git add "package.json"
            

              git commit -m "chore($(Build.Repository.Name)): bump version to $version"
              git push origin version/$clean_branch
            displayName: "⚡ Commit Version & Push"


  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      - job: "create_publish_versioning"
        displayName: "⚡ create & publish version"
        dependsOn: "deploy_micro_service"
        pool:
          vmImage: "ubuntu-22.04"
        steps:
          - task: git-tag-on-release-task@9
            displayName: "⚡ Create and Publish Versioning Tag"
            continueOnError: true
