stages:
  - stage: "change_file_detected"
    displayName: "Change File Detected"
    dependsOn: []

    variables:
      - template: ../variables/groups-transversal-variables.yml

    jobs:
      - ${{ if eq(parameters.release, 'backend') }}:
          - template: jobs/changes-file-backend.yml
            parameters:
              release: aws-ecs

      - ${{ if eq(parameters.release, 'frontend') }}:
          - template: jobs/changes-file-frontend.yml
            parameters:
              release: aws-s3
